define({
    root: {
        lblCreateSchedule: 'Create job schedule to run',
        lblEveryText: 'Every',
        lblOnText: 'on',
        lblOnTheText: 'on the',
        lblAtText: 'at',
        lblMinutesPastHour: 'minutes past the hour',
        lblFromTimeText: 'Run from',
        lblToTimeText: 'to',
        lblMinutesFrequency: 'minutes',
        lblHourlyFrequency: 'hour(s)',
        lblDailyFrequency: 'day',
        lblWeekDayFrequency: 'week day',
        lblWeeklyFrequency: 'week',
        lblMonthlyFrequency: 'month',
        lblYearlyFrequency: 'year',
        lblSunday: 'Sunday',
        lblMonday: 'Monday',
        lblTuesday: 'Tuesday',
        lblWednesday: 'Wednesday',
        lblThursday: 'Thursday',
        lblFriday: 'Friday',
        lblSaturday: 'Saturday',
        lblFirstDay: 'first',
        lblSecondDay: 'second',
        lblThirdDay: 'third',
        lblFourthDay: 'fourth',
        lblCronExpressionText: 'Cron expression',
        txtInvalidScheduleTitle: 'Invalid Schedule',
        txtInvalidDatesMessage: 'The end time must be after the start time. Please correct this information before continuing.',
        txtInvalidScheduleTime: 'The start and end times specified will prevent this schedule from running. Please correct this information before continuing.',
        txtInvalidStartDate: 'A start date is required. Please specify a start date before continuing.',
        txtInvalidEndDate: 'A end date is required. Please specify a end date before continuing'
    },
    "de": true,
    "en": true,
    "fr": true,
    "it": true,
    "ru": true
});
