define({
    loadingText: 'Загрузка...',
    moreText: 'Изменить элементы',
    clearText: 'Очистить',
    emptyText: '(пусто)',
    nullText: '(нуль)',
    ofText: '/',
    filterHasMetric: 'Имеет метрику',
    filterHasFilter: 'Имеет фильтр',
    filteroptionToday: 'Сегодня',
    filteroptionThisWeek: 'На этой неделе',
    filteroptionThisMonth: 'В этом месяце',
    filteroptionThisQuarter: 'В этот квартал',
    filteroptionThisYear: 'В этом году',
    filteroptionLastWeek: 'Последняя неделя',
    filteroptionLastMonth: 'Прошлый месяц',
    filteroptionLastQuarter: 'Прошлый квартал',
    filteroptionLastYear: 'Прошлый год',
    filteroptionWeektoStart: 'Текущая неделя',
    filteroptionMonthtoStart: 'Текущий месяц',
    filteroptionQtrtoStart: 'С начала квартала',
    filteroptionYeartoStart: 'С начала года',
    filteroptionOlder: 'Раньше'
});