define((
{
        // Add/Edit labels
        lblFilter: "Фильтр",
        lblMetric: "Метрика",
        lblFilters: "Фильтры",
        lblMetrics: "Метрики",
        lblDistinct: "Только различные",
        lblRange: "Диапазон",
        lblUserLookup: "Поиск пользователя",
        lblAdd: "Добавить",
        lblEdit: "Изменить",
        lblRemove: "Исключить",
        lblHelp: 'Помощь',
        lblFilterName: "Название фильтра",
        lblMetricName: "Название метрики",
        lblDisplayName: "Название",
        lblFilterDp: "Поля",
        lblTypeDp: "Тип",
        lblCharacter:"Символ",
        lblFrom: "От",
        lblTo: "Кому",
        lblOperators: "Операторы",
        lblAggregation: "Агрегации",
        lblTypeSpecificContentBox: "Поле данных, уникальных для типа",
        lblSaveButton: "Ок",
        lblCancelButton: "Отмена",
        DateDiffCheckerValue: "Промежуток между датами",
        InvalidFilterName: "Неправильное название фильтра",
        InvalidRangeName: "Неверное имя диапазона",
        RequiredFilterName: "Требуется имя фильтра",
        RequiredRangeName: "Требуется имя диапазона",
        FieldMustBeANumber: "Поле символа должно иметь целочисленное значение",
        SelectAnItem: "Выберите элемент",
        ItemRequired: "Требуется элемент",
        ItemInvalid: "Неверный элемент",
        LowerMustBeLessThanUpper: "Нижнее значение должно быть меньше верхнего значения.",
        defaultRangeRowValue: "Введите значение",
        totalRecordCountLabel: "Всего записей: ${0}"
    }
));