define({
    contractText: 'Contract',
    contractRequiredText: 'Contract is required',
    sdataUrlText: 'SData URL',
    titleText: 'Title',
    usernameText: 'User Name',
    passwordText: 'Password',
    logOnText: 'Log On',
    urlRequiredText: 'SData Url is required',
    urlImproperFormatText: 'SData Url has invalid format.  Example: http://localhost/sdata/slx/dynamic/-/',
    customNoAuthText1: 'We apologize for the inconvenience, but your request cannot be completed. The authorization information for this feed is incorrect or missing.',
    customNoAuthText2: 'Please update your user name and password for:',
    feedText: 'SData Feed',
    urlAuthenticationText: 'Enter a custom SData feed',
    selectFeedText: 'Select a feed',
    nextText: 'Next&gt;',
    warningText: 'Information',
    invalidWhereText: 'Sorry, the where clause is invalid.  Please review the where clause for any formatting errors. For more information see the help topic "Creating a Where Clause".',
    failedToLoadUrlText: 'Sorry, the requested feed failed to load. Please select a different feed or contact your system administrator.',
    noFeedSelectedText: 'No feed type selected',
    resourceText: 'Resource',
    whereText: 'Where Clause',
    previousText: '&lt;Back',
    noResourceSelectedText: 'Select a resource',
    noColumnsSelectedText: 'Please select one or more columns to display in your widget.',
    limitRangeText: 'Enter a value 1-100',
    testText: 'Test',
    cancelText: 'Cancel',
    finishText: 'Finish',
    exampleQueryText1: 'Example:',
    exampleQueryText2: 'machine IP address',
    exampleQueryText3: 'port number',
    exampleWhereText: 'Learn more',
    numberRecordsText: 'Visible Records',
    sageSalesLogixDynamic: 'Saleslogix Dynamic Entity',
    sageSalesLogixSystem: 'Saleslogix System',
    selectColumnsFromText: 'Available Columns:',
    selectedColumnsFromText: 'Selected Columns:'
});