define((
{ dialogCaption: 'Сведения о коммерческом предложении',
  loadingText: 'Загрузка...',
  lblSalesQuoteCaption: 'Коммерческое предложение:',
  lblStatusCaption: 'Статус:',
  lblGrossTotalCaption: 'Сумма предложения:',
  lblQuoteDateCaption: 'Дата предложения:',
  lblTaxTotalCaption: 'Налог, всего:',
  lblHoldStatusCaption: 'Статус:',
  lblCurrencyCaption: 'Валюта:',
  lblTypeCaption: 'Тип:',
  lblCostTotalCaption: 'Общая стоимость:',
  lblPONumberCaption: 'Номер заказа:',
  lblProfitTotalCaption: 'Общий доход:',
  lblQuotationCaption: 'Котировка:',
  lblInvoiceStatusCaption: 'Статус счета:',
  lblContactCaption: 'Контакт:',
  lblDeliveryDateCaption: 'Дата доставки:',
  lblDueDateCaption: 'Плановая дата:',
  lblPriceListCaption: 'Прайс-лист:',
  lblCarrierCaption: 'Перевозчик:',
  lblNetTotalCaption: 'Всего нетто:',
  lblAllocationStatusCaption: 'Статус размещения:',
  lblDiscountTotalCaption: 'Всего скидки:',
  lblDeliveryStatusCaption: 'Статус доставки:',
  lblChargesTotalCaption: 'Всего расходов:',
  detailsTabTitle: 'Детали',
  salesPersonsTabTitle: 'Продавец',
  addressTabTitle: 'Адреса',
  salesQuoteLinesTabTitle: 'Строки коммерческого предложения',
  paymentsTabTitle: 'Платежи',
  deliveriesTabTitle: 'Доставка',
  grdSalesQuote_Edit: 'Изменить',
  grdSalesQuote_QuoteNumber: 'Номер предложения',
  grdSalesQuote_QuoteDate: 'Дата предложения',
  grdSalesQuote_Status: 'Статус',
  grdSalesQuote_HoldStatus: 'Статус',
  grdSalesQuote_Type: 'Тип',
  grdSalesQuote_PO: '№ продукта заказа',
  grdSalesQuote_NetTotal: 'Сумма нетто',
  grdSalesQuote_DiscountTotal: 'Всего скидки',
  grdSalesQuote_ChargesTotal: 'Всего расходов',
  grdSalesQuote_TaxTotal: 'Налог, всего',
  grdSalesQuote_GrossTotal: 'Всего брутто',
  grdSalesQuote_Currency: 'Валюта',
  grdSalesPersons_Name: 'Имя',
  grdSalesPersons_Type: 'Тип',
  grdSalesPersons_Extension: 'Расширение',
  grdSalesPersons_Relationship: 'Связь',
  grdAddress_Name: 'Имя',
  grdAddress_Address1: 'Улица',
  grdAddress_Address2: 'Дом',
  grdAddress_City: 'Город',
  grdAddress_State: 'Область',
  grdAddress_Zip: 'Почт. индекс',
  grdItems_Line: 'Номер линии',
  grdItems_Type: 'Тип',
  grdItems_Commodity: 'Товар',
  grdItems_CommodityVariant: 'Вариант',
  grdItems_CommodityDimension: 'Размеры',
  grdItems_UnitOfMeasure: 'Единица',
  grdItems_Location: 'Размещение',
  grdItems_PriceList: 'Прайс-лист',
  grdItems_Quantity: 'Кол-во',
  grdItems_InitialPrice: 'Первоначальная цена',
  grdItems_ActualPrice: 'Фактическая цена',
  grdItems_NetTotal: 'Сумма нетто',
  grdItems_ChargesTotal: 'Всего расходов',
  grdItems_DiscountTotal: 'Всего скидки',
  grdItems_TaxTotal: 'Налог, всего',
  grdItems_GrossTotal: 'Всего брутто',
  grdPayments_Date: 'Дата оплаты',
  grdPayments_Name: 'Имя',
  grdPayments_Type: 'Тип',
  grdPayments_Status: 'Статус',
  grdPayments_NetTotal: 'Сумма нетто',
  grdPayments_Discounts: 'Скидки',
  grdPayments_Charges: 'Расходы',
  grdPayments_Tax: 'Налог',
  grdPayments_GrossTotal: 'Всего брутто',
  grdPayments_Currency: 'Валюта',
  grdPayments_TenderType: 'Тип тендера',
  grdPayments_TenderReference: 'Ссылка на тендер',
  grdPayments_ProcessDate: 'Дата обработки',
  grdDeliveries_Number: 'Число',
  grdDeliveries_Type: 'Тип',
  grdDeliveries_Status: 'Статус',
  grdDeliveries_RequestedDate: 'Требуемая дата',
  grdDeliveries_ActualDate: 'Фактическая дата',
  grdDeliveries_ActualTime: 'Фактическая время',
  grdDeliveries_RequestedQuantity: 'Требуемое количество',
  grdDeliveries_DeliveredQuantity: 'Кол-во доставленного',
  grdDeliveries_Method: 'Метод',
  grdDeliveries_Carrier: 'Перевозчик',
  grdDeliveries_CarrierReference: 'Ссылка на перевозчика',
  grdDeliveries_ExceptionReason: 'Причина исключения',
  errorERPRequest: 'При открытии подробного представления коммерческого предложения бухгалтерской системы возникла ошибка. ',
  errorERPRequestDetails: '${0}, ${1} Запрос: ${2}',
  btnCloseCaption: 'Закрыть' }
));