define({
    yestText: 'Oui',
    noText: 'Non',
    confirmOverwriteFileMsg: 'Vous avez un fichier d\'importation sélectionné actuellement. Souhaitez-vous écraser ce fichier ?',
    importProgressCaption: 'Importation des résultats de processus',
    lblPrimaryProgress: 'Traitement du fichier importé, veuillez patienter...',
    lblTotalRecords: 'Nombre total d\'enregistrements :',
    lblTotalRecordsProcessed: 'Traité :',
    lblTotalRecordsImported: 'Importé :',
    lblTotalRecordsMerged: 'Fusionné :',
    lblTotalDuplicates: 'Doublons :',
    lblTotalProjectedDuplicates: 'Doublons projetés :',
    lblDuplicateRate: 'Taux de doublons :',
    lblTotalErrors: 'Erreurs :',
    calculatingText: 'Calcul en cours, veuillez patienter...',
    importStatusProcessing: 'Traitement en cours',
    importStatusCompleted: 'Terminé',
    abortImportProcessStatus: 'Abandonner',
    btnCancelText: 'Abandonner',
    btnCloseText: 'Fermer',
    lblImportHistoryLinkText: 'Pour voir les résultats de l\'historique d\'importation, cliquez sur le numéro d\'importation ci-dessous :',
    lblImportLinkNumber: 'Numéro d\'importation : ',
    errorRequestImportHistory: 'Une erreur est survenue lors de l\'exécution de la demande sdata pour le point de terminaison HistoriqueImportation.'
});