define({
    loadingText: 'Wird geladen...',
    moreText: 'Einträge bearbeiten',
    clearText: 'Löschen',
    emptyText: '(Leer)',
    nullText: '(Null)',
    ofText: '/',
    filterHasMetric: 'Besitzt Kennzahl',
    filterHasFilter: 'Besitzt Filter',
    filteroptionToday: 'Heute',
    filteroptionThisWeek: 'Diese Woche',
    filteroptionThisMonth: 'In diesem Monat',
    filteroptionThisQuarter: 'Dieses Quartal',
    filteroptionThisYear: 'Dieses Jahr',
    filteroptionLastWeek: 'Letzte Woche',
    filteroptionLastMonth: 'Letzter Monat',
    filteroptionLastQuarter: 'Letztes Quartal',
    filteroptionLastYear: 'Letztes Jahr',
    filteroptionWeektoStart: 'Woche bis heute',
    filteroptionMonthtoStart: 'Monat Bis Heute',
    filteroptionQtrtoStart: 'Quartal bis heute',
    filteroptionYeartoStart: 'Jahr bis heute',
    filteroptionOlder: 'Älter'
});