define(
{
    txtGroup: 'Group',
    txtDateRange: 'Date Range',
    txtUser: 'User',
    txtQuery: 'Query',
    txtIsGreaterThan: 'Is Greater Than',
    txtIsLessThan: 'Is Less Than',
    txtIsInTheRange: 'Is In The Range',
    txtIsAfter: 'Is After',
    txtIsBefore: 'Is Before',
    txtContains: 'Contains',
    txtStartsWith: 'Starts With',
    txtEndsWith: 'Ends With',
    txtIs: 'Is',
    txtIsNot: 'Is Not',
    txtOnDemand: 'On Demand',
    txtScheduled: 'Scheduled',
    txtCrystalReport: 'Crystal Report',
    txtExportToFileReportType: 'Export to File',
    txtUnknownReportType: 'Unknown',
    txtNoFormat: 'No Format',
    txtPdf: 'PDF',
    txtExcel: 'Excel',
    txtExcelDataOnly: 'Excel-Data',
    txtCsv: 'CSV',
    txtWord: 'Word',
    txtXml: 'XML'
});