define((
{
        // Add/Edit labels
        lblFilter: "Filtrer",
        lblMetric: "Mesure",
        lblFilters: "Filtres",
        lblMetrics: "Mesures",
        lblDistinct: "Distinct",
        lblRange: "Plage",
        lblUserLookup: "Rechercher un utilisateur",
        lblAdd: "Ajouter",
        lblEdit: "Modifier",
        lblRemove: "Retirer",
        lblHelp: 'Aide',
        lblFilterName: "Nom du filtre",
        lblMetricName: "Nom de la mesure",
        lblDisplayName: "Nom d'affichage",
        lblFilterDp: "Champs",
        lblTypeDp: "Type",
        lblCharacter:"Caractère",
        lblFrom: "De",
        lblTo: "À",
        lblOperators: "Opérateurs",
        lblAggregation: "Agrégations",
        lblTypeSpecificContentBox: "Zone de contenu spécifique de type",
        lblSaveButton: "OK",
        lblCancelButton: "Annuler",
        DateDiffCheckerValue: "Mesure de différence de date",
        InvalidFilterName: "Nom de filtre non valide",
        InvalidRangeName: "Nom de plage incorrect",
        RequiredFilterName: "Nom de filtre obligatoire",
        RequiredRangeName: "Nom de plage obligatoire",
        FieldMustBeANumber: "Le champ Caractère doit être un nombre entier.",
        SelectAnItem: "Sélectionnez un élément",
        ItemRequired: "Elément obligatoire",
        ItemInvalid: "Elément incorrect",
        LowerMustBeLessThanUpper: "La valeur la plus basse doit être inférieure à la valeur la plus haute.",
        defaultRangeRowValue: "Saisir une valeur",
        totalRecordCountLabel: "Nombre total d'enregistrements : ${0}"
    }
));