define({
    contractText: 'Vertrag',
    contractRequiredText: 'Vertrag ist erforderlich',
    sdataUrlText: 'SData-URL',
    titleText: 'Titel',
    usernameText: 'Benutzername',
    passwordText: 'Passwort',
    logOnText: 'Anmelden',
    urlRequiredText: 'SData-URL ist erforderlich',
    urlImproperFormatText: 'SData-URL hat ein ungültiges Format.  Beispiel: http://localhost/sdata/slx/dynamic/-/',
    customNoAuthText1: 'Wir entschuldigen uns für die Unannehmlichkeiten, aber Ihre Anforderung kann nicht abgeschlossen werden. Die Autorisierungsdaten für diesen Feed sind falsch oder fehlen.',
    customNoAuthText2: 'Aktualisieren Sie Ihren Benutzernamen und Ihr Kennwort für:',
    feedText: 'SData-Feed',
    urlAuthenticationText: 'Benutzerdefinierten SData-Feed eingeben',
    selectFeedText: 'Feed auswählen',
    nextText: 'Weiter&gt;',
    warningText: 'Informationen',
    invalidWhereText: 'Leider ist die where-Klausel ungültig. Überprüfen Sie die where-Klausel für alle Formatierungsfehler. Weitere Informationen finden Sie im Hilfethema "Erstellen einer Where-Klausel".',
    failedToLoadUrlText: 'Leider konnte der angeforderte Feed nicht geladen weren. Wählen Sie einen anderen Feed, oder wenden Sie sich an Ihren Systemadministrator.',
    noFeedSelectedText: 'Kein Feed-Typ ausgewählt',
    resourceText: 'Ressource',
    whereText: 'WHERE-Klausel',
    previousText: '&lt;Zurück',
    noResourceSelectedText: 'Ressource auswählen',
    noColumnsSelectedText: 'Wählen Sie eine oder mehrere Spalten zur Anzeige in Ihrem Widget aus.',
    limitRangeText: 'Wert zwischen 1 und 100 eingeben',
    testText: 'Test',
    cancelText: 'Abbrechen',
    finishText: 'Fertig stellen',
    exampleQueryText1: 'Beispiel:',
    exampleQueryText2: 'IP-Adresse des Computers',
    exampleQueryText3: 'Portnummer',
    exampleWhereText: 'Mehr erfahren',
    numberRecordsText: 'Sichtbare Datensätze',
    sageSalesLogixDynamic: 'Dynamische Saleslogix-Entität',
    sageSalesLogixSystem: 'Saleslogix-System',
    selectColumnsFromText: 'Verfügbare Spalten:',
    selectedColumnsFromText: 'Ausgewählte Spalten:'
});