define({
    SelectRecordMsg: 'Prima di continuare è necessario selezionare almeno un record.',
    SelectRecordMsgSingle: 'È necessario selezionare un unico record prima di continuare.',
    ConfirmDeletionMsg: '${0} il ${1} selezionato?',
    SelectedGroups: 'gruppi (inclusi condivisi)',
    SelectedReleases: 'gruppi condivisi',
    SelectedStatistics: 'Statistiche di gruppo',
    Yes: 'Sì',
    No: 'No',
    Reset: 'Reimposta',
    Delete: 'Elimina',
    InvalidSelectedGroup: 'Il gruppo selezionato è una condivisione. Selezionare un gruppo di proprietà dell\'utente o sul quale l\'utente abbia il controllo e che non sia una condivisione.',
    NotDeveloperGroup: 'Il gruppo selezionato non è più in fase di sviluppo.',
    NotGroupOwner: 'Il gruppo selezionato non è di proprietà dell\'utente. Selezionare un gruppo di proprietà dell\'utente o sul quale l\'utente abbia il controllo.',
    OK: 'OK',
    SelectOwner: 'Select Owner',
    FirstName: 'Nome',
    LastName: 'Cognome',
    UserName: 'Nome Utente',
    Type: 'Tipo'
});