define({
    root: {
        // Add/Edit labels
        lblFilter: "Filter",
        lblMetric: "Metric",
        lblFilters: "Filters",
        lblMetrics: "Metrics",
        lblDistinct: "Distinct",
        lblRange: "Range",
        lblUserLookup: "User Lookup",
        lblAdd: "Add",
        lblEdit: "Edit",
        lblRemove: "Remove",
        lblHelp: 'Help',
        lblFilterName: "Filter Name",
        lblMetricName: "Metric Name",
        lblDisplayName: "Display Name",
        lblFilterDp: "Fields",
        lblTypeDp: "Type",
        lblCharacter: "Characters",
        lblFrom: "From",
        lblTo: "To",
        lblOperators: "Operators",
        lblAggregation: "Aggregations",
        lblTypeSpecificContentBox: "Type Specific Content Box",
        lblSaveButton: "OK",
        lblCancelButton: "Cancel",
        DateDiffCheckerValue: "Date Difference Metric",
        InvalidFilterName: "Invalid filter name",
        InvalidRangeName: "Invalid range name",
        RequiredFilterName: "Filter name is required",
        RequiredRangeName: "Range name is required",
        FieldMustBeANumber: "Character field must be integer",
        SelectAnItem: "Please select an item",
        ItemRequired: "Item required",
        ItemInvalid: "Item invalid",
        LowerMustBeLessThanUpper: "Lower value must be less than upper value.",
        defaultRangeRowValue: "Enter a value",
        totalRecordCountLabel: "Total Records: ${0}"
    },
    "de": true,
    "en": true,
    "fr": true,
    "it": true,
    "ru": true
});