define((
{ dialogCaption: 'Dettagli preventivo vendita',
  loadingText: 'Caricamento...',
  lblSalesQuoteCaption: 'Preventivo vendita:',
  lblStatusCaption: 'Status:',
  lblGrossTotalCaption: 'Importo preventivo:',
  lblQuoteDateCaption: 'Data preventivo:',
  lblTaxTotalCaption: 'Totale Tassa:',
  lblHoldStatusCaption: 'Status Possesso:',
  lblCurrencyCaption: 'Valuta:',
  lblTypeCaption: 'Tipo:',
  lblCostTotalCaption: 'Costo Totale:',
  lblPONumberCaption: 'Ordine Acquisto N.:',
  lblProfitTotalCaption: 'Profitto Totale:',
  lblQuotationCaption: 'Offerta:',
  lblInvoiceStatusCaption: 'Status Fattura:',
  lblContactCaption: 'Contatto:',
  lblDeliveryDateCaption: 'Data Consegna:',
  lblDueDateCaption: 'Scadenza:',
  lblPriceListCaption: 'Prezzo di Listino:',
  lblCarrierCaption: 'Vettore:',
  lblNetTotalCaption: 'Totale Netto:',
  lblAllocationStatusCaption: 'Status Allocazione:',
  lblDiscountTotalCaption: 'Totale Sconto:',
  lblDeliveryStatusCaption: 'Status Consegna:',
  lblChargesTotalCaption: 'Spese Totali:',
  detailsTabTitle: 'Dettagli',
  salesPersonsTabTitle: 'Agente di Vendite:',
  addressTabTitle: 'Indirizzi',
  salesQuoteLinesTabTitle: 'Righe preventivo vendita',
  paymentsTabTitle: 'Pagamenti',
  deliveriesTabTitle: 'Consegne',
  grdSalesQuote_Edit: 'Modifica',
  grdSalesQuote_QuoteNumber: 'Numero preventivo',
  grdSalesQuote_QuoteDate: 'Data preventivo',
  grdSalesQuote_Status: 'Status',
  grdSalesQuote_HoldStatus: 'In possesso dello Status',
  grdSalesQuote_Type: 'Tipo',
  grdSalesQuote_PO: 'Ordine Acquisto N.',
  grdSalesQuote_NetTotal: 'Totale Netto',
  grdSalesQuote_DiscountTotal: 'Totale Sconto',
  grdSalesQuote_ChargesTotal: 'Totale Oneri',
  grdSalesQuote_TaxTotal: 'Totale Tassa',
  grdSalesQuote_GrossTotal: 'Totale Lordo',
  grdSalesQuote_Currency: 'Valuta',
  grdSalesPersons_Name: 'Nome',
  grdSalesPersons_Type: 'Tipo',
  grdSalesPersons_Extension: 'Estensione',
  grdSalesPersons_Relationship: 'Relazione',
  grdAddress_Name: 'Nome',
  grdAddress_Address1: 'Indirizzo 1',
  grdAddress_Address2: 'Indirizzo 2',
  grdAddress_City: 'Città',
  grdAddress_State: 'Status',
  grdAddress_Zip: 'Cap',
  grdItems_Line: 'Numero Linea',
  grdItems_Type: 'Tipo',
  grdItems_Commodity: 'Merce',
  grdItems_CommodityVariant: 'Variante',
  grdItems_CommodityDimension: 'Dimensione',
  grdItems_UnitOfMeasure: 'Unità',
  grdItems_Location: 'Posizione',
  grdItems_PriceList: 'Listino prezzi',
  grdItems_Quantity: 'Quantità',
  grdItems_InitialPrice: 'Prezzo Iniziale',
  grdItems_ActualPrice: 'Prezzo Attuale',
  grdItems_NetTotal: 'Totale Netto',
  grdItems_ChargesTotal: 'Totale Oneri',
  grdItems_DiscountTotal: 'Totale Sconto',
  grdItems_TaxTotal: 'Totale Tassa',
  grdItems_GrossTotal: 'Totale Lordo',
  grdPayments_Date: 'Data Pagamento',
  grdPayments_Name: 'Nome',
  grdPayments_Type: 'Tipo',
  grdPayments_Status: 'Status',
  grdPayments_NetTotal: 'Totale Netto',
  grdPayments_Discounts: 'Sconti',
  grdPayments_Charges: 'Oneri',
  grdPayments_Tax: 'Tassa',
  grdPayments_GrossTotal: 'Totale Lordo',
  grdPayments_Currency: 'Valuta',
  grdPayments_TenderType: 'Tipo Offerta',
  grdPayments_TenderReference: 'Riferimento Offerta',
  grdPayments_ProcessDate: 'Data Processo',
  grdDeliveries_Number: 'Numero',
  grdDeliveries_Type: 'Tipo',
  grdDeliveries_Status: 'Status',
  grdDeliveries_RequestedDate: 'Data Richiesta',
  grdDeliveries_ActualDate: 'Data Attuale',
  grdDeliveries_ActualTime: 'Orario Attuale',
  grdDeliveries_RequestedQuantity: 'Quantità Richiesta',
  grdDeliveries_DeliveredQuantity: 'Quantità Consegnata',
  grdDeliveries_Method: 'Metodo',
  grdDeliveries_Carrier: 'Vettore',
  grdDeliveries_CarrierReference: 'Riferimento Vettore',
  grdDeliveries_ExceptionReason: 'Motivo Eccezione',
  errorERPRequest: 'Si è verificato un errore durante l\'apertura della vista dettagli preventivo vendita del sistema di contabilità. ',
  errorERPRequestDetails: '${0}, ${1} Richiesto: ${2}',
  btnCloseCaption: 'Chiudi' }
));