define({
    txtPleaseSpecifyValue: 'Veuillez indiquer une valeur.',
    lblAvailableValues_Caption: 'Valeurs disponibles :',
    lblSelectedValues_Caption: 'Valeurs sélectionnées :',
    lblEnterValue_Caption: 'Entrer une valeur :',
    btnOK_Caption: 'OK',
    txtTheValueMustBeBetween: 'La valeur doit contenir entre {0} et {1} caractères.',
    txtTheMinimumLengthForThisField: 'La longueur minimale pour ce champ est de {0}.',
    txtTheMaximumLengthForThisField: 'La longueur maximale pour ce champ est de {0}.',
    txtPleaseSpecifyNumberBetween: 'Veuillez indiquer une valeur numérique comprise entre {0} et {1}.',
    txtPleaseSpecifyNumberLesser: 'Veuillez indiquer une valeur numérique inférieure ou égale à {0}.',
    txtPleaseSpecifyNumberGreater: 'Veuillez indiquer une valeur numérique supérieure ou égale à {0}.',
    txtNoLowerValue: 'Aucune valeur inférieure',
    txtNoUpperValue: 'Aucune valeur supérieure',
    txtIncludeThisValue: 'Inclure cette valeur',
    txtFrom: 'De :',
    txtTo: 'A :',
    txtPleaseSpecifyFromValue: 'Spécifiez une valeur pour la plage de début',
    txtPleaseSpecifyToValue: 'Spécifiez une valeur pour la plage de fin',
    txtPleaseSpecifyDateBetween: 'Veuillez indiquer une valeur de date comprise entre {0} et {1}.',
    txtPleaseSpecifyDateLesser: 'Veuillez indiquer une valeur de date inférieure ou égale à {0}.',
    txtPleaseSpecifyDateGreater: 'Veuillez indiquer une valeur de date supérieure ou égale à {0}.',
    txtFromMustBeLessThanOrEqualToTo: 'La valeur de plage de début doit être inférieure ou égale à la valeur de plage de fin.',
    txtStartOfRange: 'Début de la plage :',
    txtEndOfRange: 'Fin de la plage :',
    txtAddRange: 'Ajouter un intervalle',
    lblSelectValue_Caption: 'Sélectionner une valeur :',
    lblOrValue_Caption: 'Ou'
});