define((
{ dlgCrystalReportConditionDetails_Title: 'Ajouter/modifier une condition',
  cmdOK_Caption: 'OK',
  cmdCancel_Caption: 'Annuler',
  cmbConditionType_Caption: 'Rechercher par',
  txtInvalidParameterTitle: 'Paramètre non valide',
  txtInvalidParameterMessage: 'Paramètre non valide : ${0}',
  lkpUser_Caption: 'Utilisateur',
  lkpGroup_Caption: 'Groupe',
  txtSelectUser: 'Sélectionner un utilisateur',
  chkCurrentUser_Caption: 'Utilisateur actuel',
  txtName: 'Nom',
  txtOK: 'OK',
  txtSelectGroup: 'Sélectionner un groupe',
  cmbDateRange_Caption: 'Intervalle de dates',
  cmbDateRange_SpecificDates_Caption: 'Dates spécifiques',
  cmbDateRange_ThisWeek_Caption: 'Cette semaine',
  cmbDateRange_ThisMonth_Caption: 'Ce mois',
  cmbDateRange_ThisQuarter_Caption: 'Ce trimestre',
  cmbDateRange_ThisYear_Caption: 'Cette année',
  cmbDateRange_LastWeek_Caption: 'Semaine dernière',
  cmbDateRange_LastMonth_Caption: 'Mois dernier',
  cmbDateRange_LastQuarter_Caption: 'Trimestre dernier',
  cmbDateRange_LastYear_Caption: 'Année dernière',
  cmbDateRange_MonthToDate_Caption: 'Mois à ce jour',
  cmbDateRange_QuarterToDate_Caption: 'Trimestre à ce jour',
  cmbDateRange_YearToDate_Caption: 'Année à ce jour',
  dtFromDate_Caption: 'De',
  dtToDate_Caption: 'À',
  cmbTable_Caption: 'Table',
  cmbField_Caption: 'Champ',
  cmbOperator_Caption: 'Opérateur',
  txtValue_Caption: 'Valeur',
  txtNumericValueFrom_Caption: 'De',
  txtNumericValueTo_Caption: 'À' }
));