define({
    lblCreateSchedule: 'Crea pianificazione lavori da eseguire',
    lblEveryText: 'Ogni',
    lblOnText: 'su',
    lblOnTheText: 'il',
    lblAtText: 'a',
    lblMinutesPastHour: 'minuti dopo l\'ora',
    lblFromTimeText: 'Esegui da',
    lblToTimeText: 'A',
    lblMinutesFrequency: 'Minuti',
    lblHourlyFrequency: 'Ora(e)',
    lblDailyFrequency: 'Giorno',
    lblWeekDayFrequency: 'giorno feriale',
    lblWeeklyFrequency: 'Settimana',
    lblMonthlyFrequency: 'Mese',
    lblYearlyFrequency: 'Anno',
    lblSunday: 'Domenica',
    lblMonday: 'Lunedì',
    lblTuesday: 'Martedì',
    lblWednesday: 'Mercoledì',
    lblThursday: 'Giovedì',
    lblFriday: 'Venerdì',
    lblSaturday: 'Sabato',
    lblFirstDay: 'Nome',
    lblSecondDay: 'secondo',
    lblThirdDay: 'terzo',
    lblFourthDay: 'quarto',
    lblCronExpressionText: 'Espressione Cron',
    txtInvalidScheduleTitle: 'Pianificazione non valida',
    txtInvalidDatesMessage: 'L\'ora di fine deve essere successiva all\'ora di inizio. Correggere questa informazione prima di continuare.',
    txtInvalidScheduleTime: 'Le ore di inizio e fine specificate impediranno l\'esecuzione di questa pianificazione. Correggere questa informazione prima di continuare.',
    txtInvalidStartDate: 'La data di inizio è obbligatoria. Specificare una data di inizio prima di continuare.',
    txtInvalidEndDate: 'La data di fine è obbligatoria. Specificare una data di inizio prima di continuare.'
});