define(
    {
        txtGroupFamily_Caption: 'Семейство:',
        txtGroupName_Caption: 'Имя:',
        txtGroupDisplayName_Caption: 'Название:',
        txtGroupDescription_Caption: 'Описание:',
        txtGroupId_Caption: 'ИД:',
        txtGroupMainTable_Caption: 'Основная таблица:',
        txtGroupEntityName_Caption: 'Имя сущности:',
        txtGroupCreateDate_Caption: 'Дата создания:',
        txtGroupCreateUser_Caption: 'Создано:',
        txtGroupModifyDate_Caption: 'Дата изменения:',
        txtGroupModifyUser_Caption: 'Изменил:',
        txtGroupInstallationDate_Caption: 'Дата установки:',
        txtGroupShared_Caption: 'Разделено:',
        txtGroupSharedDate_Caption: 'Дата открытия общего доступа:',
        txtGroupOwner_Caption: 'Куратор:',
        txtGroupUserId_Caption: 'ИД пользователя:',
        txtGroupAdhoc_Caption: 'Спец. группа:',
        txtGroupHidden_Caption: 'Скрытый:',
        txtGroupAuthor_Caption: 'Автор:',
        txtGroupCompany_Caption: 'Компания:',
        txtGroupCompanyVersion_Caption: 'Версия Компании:',
        txtGroupDev_Caption: 'Разраб.:',
        txtGroupDataCode_Caption: 'Код данных:',
        txtGroupType_Caption: 'Тип группы:',
        txtGroupBasedOn_Caption: 'ИД базовой группы:',
        txtGroupReleasedToType_Caption: 'Тип получателя общего доступа:',
        txtGroupReleasedTo_Caption: 'Имя получателя общего доступа:',
        txtGroupReleasedToTitle_Caption: 'Название ресурса общего доступа:',
        txtGroupReleasedToUserType_Caption: 'Тип пользователя ресурса общего доступа:'
    }
);