define((
{ dlgCrystalReportConditionDetails_Title: 'Add/Edit Condition',
  cmdOK_Caption: 'OK',
  cmdCancel_Caption: 'Cancel',
  cmbConditionType_Caption: 'Match By',
  txtInvalidParameterTitle: 'Invalid Parameter',
  txtInvalidParameterMessage: 'Invalid Parameter: ${0}',
  lkpUser_Caption: 'User',
  lkpGroup_Caption: 'Group',
  txtSelectUser: 'Select User',
  chkCurrentUser_Caption: 'Current User',
  txtName: 'Name',
  txtOK: 'OK',
  txtSelectGroup: 'Select Group',
  cmbDateRange_Caption: 'Date Range',
  cmbDateRange_SpecificDates_Caption: 'Specific Dates',
  cmbDateRange_ThisWeek_Caption: 'This Week',
  cmbDateRange_ThisMonth_Caption: 'This Month',
  cmbDateRange_ThisQuarter_Caption: 'This Quarter',
  cmbDateRange_ThisYear_Caption: 'This Year',
  cmbDateRange_LastWeek_Caption: 'Last Week',
  cmbDateRange_LastMonth_Caption: 'Last Month',
  cmbDateRange_LastQuarter_Caption: 'Last Quarter',
  cmbDateRange_LastYear_Caption: 'Last Year',
  cmbDateRange_MonthToDate_Caption: 'Month to Date',
  cmbDateRange_QuarterToDate_Caption: 'Quarter to Date',
  cmbDateRange_YearToDate_Caption: 'Year to Date',
  dtFromDate_Caption: 'From',
  dtToDate_Caption: 'To',
  cmbTable_Caption: 'Table',
  cmbField_Caption: 'Field',
  cmbOperator_Caption: 'Operator',
  txtValue_Caption: 'Value',
  txtNumericValueFrom_Caption: 'From',
  txtNumericValueTo_Caption: 'To' }
));