define(
    {
        txtGroupFamily_Caption: 'Famiglia:',
        txtGroupName_Caption: 'Nome:',
        txtGroupDisplayName_Caption: 'Visualizza nome:',
        txtGroupDescription_Caption: 'Descrizione:',
        txtGroupId_Caption: 'ID:',
        txtGroupMainTable_Caption: 'Tabella principale:',
        txtGroupEntityName_Caption: 'Entity Name:',
        txtGroupCreateDate_Caption: 'Data creazione:',
        txtGroupCreateUser_Caption: 'Creato da:',
        txtGroupModifyDate_Caption: 'Data Modifica:',
        txtGroupModifyUser_Caption: 'Utente Modifica:',
        txtGroupInstallationDate_Caption: 'Data installazione:',
        txtGroupShared_Caption: 'Condiviso:',
        txtGroupSharedDate_Caption: 'Data condivisione:',
        txtGroupOwner_Caption: 'Proprietario:',
        txtGroupUserId_Caption: 'ID utente:',
        txtGroupAdhoc_Caption: 'Ad hoc:',
        txtGroupHidden_Caption: 'Nascosto:',
        txtGroupAuthor_Caption: 'Autore:',
        txtGroupCompany_Caption: 'Società:',
        txtGroupCompanyVersion_Caption: 'Company Version:',
        txtGroupDev_Caption: 'Svil:',
        txtGroupDataCode_Caption: 'Codice dati:',
        txtGroupType_Caption: 'Tipo Gruppo:',
        txtGroupBasedOn_Caption: 'Basato su ID gruppo:',
        txtGroupReleasedToType_Caption: 'Condiviso in Tipo:',
        txtGroupReleasedTo_Caption: 'Condiviso in Nome:',
        txtGroupReleasedToTitle_Caption: 'Condiviso in Titolo:',
        txtGroupReleasedToUserType_Caption: 'Condiviso in Tipo utente:'
    }
);