define((
{ dlgReportScheduleDetails_Schedule_Title: 'Zeitplan hinzufügen/bearbeiten',
  dlgReportScheduleDetails_RunReport_Title: 'Bericht ausführen',
  txtReportType_Caption: 'Berichtstyp',
  txtReportName_Caption: 'Berichtsname',
  txtOutputFormat_Caption: 'Format ',
  txtRunAs_Caption: 'Ausführen als',
  txtScheduleName_Caption: 'Zeitplan-Name',
  txtScheduleDescription_Caption: 'Beschreibung',
  cmbScheduleFrequency_Caption: 'Häufigkeit',
  cmbArchive_Caption: 'Berichte archivieren, die älter sind als',
  dtStartTime_Caption: 'Ausführen von',
  dtEndTime_Caption: 'Ausführen bis',
  txtRepeatCount_Caption: 'Anzahl Wiederholungen',
  txtRepeatInterval_Caption: 'Wiederholungsintervall',
  cmdOK_Caption: 'OK',
  cmdCancel_Caption: 'Abbrechen',
  tabSchedule_Caption: 'Zeitplan-Details',
  txtOnDemandScheduleName: 'Auf Anforderung',
  txtReportSuccessfullyScheduled: 'Bericht erfolgreich geplant.',
  dlgScheduleReport_Title: 'Bericht planen',
  txtName: 'Name',
  txtSelectUser: 'Benutzer auswählen',
  txtOK: 'OK' }
));