define({
    txtPleaseSpecifyValue: 'Der Von-Wert muss kleiner als der Bis-Wert oder gleich sein',
    lblAvailableValues_Caption: 'Verfügbare Werte:',
    lblSelectedValues_Caption: 'Ausgewählte Werte:',
    lblEnterValue_Caption: 'Wert eingeben:',
    btnOK_Caption: 'OK',
    txtTheValueMustBeBetween: 'Der Wert muss aus {0} bis {1} Zeichen bestehen.',
    txtTheMinimumLengthForThisField: 'Die minimale Länge für dieses Feld beträgt {0}.',
    txtTheMaximumLengthForThisField: 'Die maximale Länge für dieses Feld beträgt {0}.',
    txtPleaseSpecifyNumberBetween: 'Geben Sie einen Zahlenwert zwischen {0} und {1} an.',
    txtPleaseSpecifyNumberLesser: 'Geben Sie einen Zahlenwert an, der kleiner oder gleich {0} ist.',
    txtPleaseSpecifyNumberGreater: 'Geben Sie einen Zahlenwert an, der größer oder gleich {0} ist.',
    txtNoLowerValue: 'Kein niedrigeren Werte',
    txtNoUpperValue: 'Kein oberen Werte',
    txtIncludeThisValue: 'Fügen Sie diesen Wert hinzu',
    txtFrom: 'Von:',
    txtTo: 'Bis:',
    txtPleaseSpecifyFromValue: 'Geben Sie einen Startbereichswert ein',
    txtPleaseSpecifyToValue: 'Geben Sie einen Endbereichswert ein',
    txtPleaseSpecifyDateBetween: 'Geben Sie einen Datumswert zwischen {0} und {1} an.',
    txtPleaseSpecifyDateLesser: 'Geben Sie einen Datumswert an, der kleiner oder gleich {0} ist.',
    txtPleaseSpecifyDateGreater: 'Geben Sie einen Datumswert an, der größer oder gleich {0} ist.',
    txtFromMustBeLessThanOrEqualToTo: 'Der Startbereichswert muss kleiner als der Endbereichswert sein oder gleich',
    txtStartOfRange: 'Start des Bereichs:',
    txtEndOfRange: 'Ende des Bereichs:',
    txtAddRange: 'Bereich hinzufügen',
    lblSelectValue_Caption: 'Wählen Sie einen Wert:',
    lblOrValue_Caption: 'Oder'
});