define((
{ txtErrorActionMsg: 'I mi dispiace, l\'azione non ha avuto successo si è verificato un errore.',
  txtActivity: 'Attività',
  txtActivities: 'Attività',
  txtActionDeleteActivites: 'Elimina Attività',
  txtActionDeleteActivitiesQuestion: 'Verranno eliminate solo le attività di cui hai l\'autorizzazione all\'eliminazione.<P>Sei sicuro di voler eliminare il   {0} selezionato   {1}?',
  txtAlarm: 'Allarme',
  txtAlarms: 'Allarmi',
  txtActionSnoozeAlarm: 'Posticipa Allarme',
  txtActionSnoozeQuestion: 'Sei sicuro di voler posporre il {0} selezionato {1} per {2} ?',
  txtActionSnoozeAllQuestion: 'Sei sicuro di voler posporre tutti {0} per {1} ?',
  txtActionDismissAlarms: 'Respingi allarmi',
  txtActionDismissAlarmsQuestion: 'Sei sicuro di voler respingere il   {0} selezionato   {1}?',
  txtEvent: 'Evento',
  txtEvents: 'Eventi',
  txtActionDeleteEvents: 'Eliminare gli eventi',
  txtActionDeleteEventsQuestion: 'Verranno eliminati solo gli eventi di cui hai l\'autorizzazione all\'eliminazione.<P>Sei sicuro di voler eliminare il   {0} selezionato   {1}?',
  txtConfirmation: 'conferma',
  txtConfirmations: 'Conferme',
  txtActionAcceptConfirmations: 'Accettare le conferme',
  txtActionAcceptConfirmQuestion: 'Sei sicuro di voler accettare che le   {0} selezionato   {1}? Questa azione può essere eseguita solo su nuove conferme. Tutti gli altri verranno ignorati. ',
  txtDeclineConfirmations: 'Rifiutare le conferme',
  txtActionDeclineConfrimQuestion: 'Sei sicuro che vuoi declinare il   {0} selezionato   {1}? Questa azione può essere eseguita solo su nuove conferme. Tutti gli altri verranno ignorati. ',
  txtActionRemoveConfirmations: 'Elimina conferme',
  txtActionRemoveConfirmationsQuestion: 'Eliminare il {0} selezionato {1}? Questa azione può essere eseguita solo su conferme Leader, Rifiutate o Eliminate. Tutte le altre verranno ignorate.',
  txtLiteratureRequest: 'Richiesta materiale informativo',
  txtLiteratureRequests: 'Richieste di materiale informativo',
  txtActionDeleteLiteratureRequests: 'Eliminare le richieste di materiale informativo',
  txtActionDeleteLiteratureRequestsQuestion: 'Verranno eliminate solo le richieste di materiale informativo di cui hai l\'autorizzazione all\'eliminazione.<P>Sei sicuro di voler eliminare il   {0} selezionato   {1}?' }
));