define({
    lblCreateSchedule: 'Создать расписание задания для запуска',
    lblEveryText: 'Каждый',
    lblOnText: 'в',
    lblOnTheText: 'в',
    lblAtText: 'в',
    lblMinutesPastHour: 'мин. после часа',
    lblFromTimeText: 'Выполнять с',
    lblToTimeText: 'по',
    lblMinutesFrequency: 'мин.',
    lblHourlyFrequency: 'ч.',
    lblDailyFrequency: 'дн.',
    lblWeekDayFrequency: 'будний день',
    lblWeeklyFrequency: 'нед.',
    lblMonthlyFrequency: 'мес.',
    lblYearlyFrequency: 'г.',
    lblSunday: 'Воскресенье',
    lblMonday: 'Понедельник',
    lblTuesday: 'Вторник',
    lblWednesday: 'Среда',
    lblThursday: 'Четверг',
    lblFriday: 'Пятница',
    lblSaturday: 'Суббота',
    lblFirstDay: '1',
    lblSecondDay: '2',
    lblThirdDay: '3',
    lblFourthDay: '4',
    lblCronExpressionText: 'Cron-выражение',
    txtInvalidScheduleTitle: 'Недопустимое расписание',
    txtInvalidDatesMessage: 'Время окончания не может быть раньше времени начала. Исправьте эту информацию перед продолжением.',
    txtInvalidScheduleTime: 'Указанное время начала и окончания не позволяет выполнить это расписание. Исправьте эту информацию перед продолжением.',
    txtInvalidStartDate: 'Требуется дата начала. Укажите дату начала перед продолжением.',
    txtInvalidEndDate: 'Требуется дата окончания. Укажите дату окончания перед продолжением.'
});