define(
{
    txtGroup: 'Gruppe',
    txtDateRange: 'Datumsbereich',
    txtUser: 'Benutzer',
    txtQuery: 'Abfrage',
    txtIsGreaterThan: 'Ist größer als',
    txtIsLessThan: 'Ist kleiner als',
    txtIsInTheRange: 'Liegt im Bereich',
    txtIsAfter: 'Kommt nach',
    txtIsBefore: 'Kommt vor',
    txtContains: 'Enthält',
    txtStartsWith: 'Beginnt mit',
    txtEndsWith: 'Endet mit',
    txtIs: 'Ist',
    txtIsNot: 'Ist nicht',
    txtOnDemand: 'Auf Anforderung',
    txtScheduled: 'Geplant',
    txtCrystalReport: 'Crystal-Bericht',
    txtExportToFileReportType: 'In Datei exportieren',
    txtUnknownReportType: 'Unbekannt',
    txtNoFormat: 'Kein Format',
    txtPdf: 'PDF',
    txtExcel: 'Excel',
    txtExcelDataOnly: 'Excel-Daten',
    txtCsv: 'CSV',
    txtWord: 'Word',
    txtXml: 'XML'
});