define({
    txtPleaseSpecifyValue: 'Укажите значение.',
    lblAvailableValues_Caption: 'Доступные значения:',
    lblSelectedValues_Caption: 'Выбранные значения:',
    lblEnterValue_Caption: 'Введите значение:',
    btnOK_Caption: 'Ок',
    txtTheValueMustBeBetween: 'Длина значения должна составлять от {0} до {1} символов.',
    txtTheMinimumLengthForThisField: 'Минимальная длина этого поля - {0}.',
    txtTheMaximumLengthForThisField: 'Максимальная длина этого поля - {0}.',
    txtPleaseSpecifyNumberBetween: 'Укажите значение числа в диапазоне от {0} до {1}.',
    txtPleaseSpecifyNumberLesser: 'Укажите значение числа, меньшее или равное {0}.',
    txtPleaseSpecifyNumberGreater: 'Укажите значение числа, большее или равное {0}.',
    txtNoLowerValue: 'Нет меньшего значения',
    txtNoUpperValue: 'Нет большего значения',
    txtIncludeThisValue: 'Включить это значение',
    txtFrom: 'От:',
    txtTo: 'Кому:',
    txtPleaseSpecifyFromValue: 'Укажите значение начала диапазона',
    txtPleaseSpecifyToValue: 'Укажите значение конца диапазона',
    txtPleaseSpecifyDateBetween: 'Укажите значение даты в диапазоне от {0} до {1}.',
    txtPleaseSpecifyDateLesser: 'Укажите значение даты, меньшее или равное {0}.',
    txtPleaseSpecifyDateGreater: 'Укажите значение даты, большее или равное {0}.',
    txtFromMustBeLessThanOrEqualToTo: 'Значение начала диапазона должно быть меньше или равно значению конца диапазона.',
    txtStartOfRange: 'Начало диапазона:',
    txtEndOfRange: 'Конец диапазона:',
    txtAddRange: 'Добавить диапазон',
    lblSelectValue_Caption: 'Выберите значение:',
    lblOrValue_Caption: 'Или'
});