define((
{ dlgCrystalReportConditionDetails_Title: 'Добавить/изменить условия',
  cmdOK_Caption: 'Ок',
  cmdCancel_Caption: 'Отмена',
  cmbConditionType_Caption: 'Поиск по',
  txtInvalidParameterTitle: 'Недопустимый параметр',
  txtInvalidParameterMessage: 'Недопустимый параметр: ${0}',
  lkpUser_Caption: 'Пользователь',
  lkpGroup_Caption: 'Группа',
  txtSelectUser: 'Выберите польз.',
  chkCurrentUser_Caption: 'Текущий пользователь',
  txtName: 'Имя',
  txtOK: 'Ок',
  txtSelectGroup: 'Выбрать Группу',
  cmbDateRange_Caption: 'Временной диапазон',
  cmbDateRange_SpecificDates_Caption: 'Точная дата',
  cmbDateRange_ThisWeek_Caption: 'На этой неделе',
  cmbDateRange_ThisMonth_Caption: 'В этом месяце',
  cmbDateRange_ThisQuarter_Caption: 'В этот квартал',
  cmbDateRange_ThisYear_Caption: 'В этом году',
  cmbDateRange_LastWeek_Caption: 'Последняя неделя',
  cmbDateRange_LastMonth_Caption: 'Прошлый месяц',
  cmbDateRange_LastQuarter_Caption: 'Прошлый квартал',
  cmbDateRange_LastYear_Caption: 'Прошлый год',
  cmbDateRange_MonthToDate_Caption: 'Текущий месяц',
  cmbDateRange_QuarterToDate_Caption: 'С начала квартала',
  cmbDateRange_YearToDate_Caption: 'С начала года',
  dtFromDate_Caption: 'От',
  dtToDate_Caption: 'Кому',
  cmbTable_Caption: 'Таблица',
  cmbField_Caption: 'Поле',
  cmbOperator_Caption: 'Оператор',
  txtValue_Caption: 'Значение',
  txtNumericValueFrom_Caption: 'От',
  txtNumericValueTo_Caption: 'Кому' }
));