define({
    typeText: 'Тип',
    showDbChangesText: 'Отобразить изменения в БД',
    selectAllText: 'Выбрать все',
    dateText: 'Дата',
    dateTimeText: 'Дата/Время',
    dateRangeText: 'Временной диапазон',
    userText: 'Пользователь',
    accountText: 'Субъект',
    contactText: 'Контакт',
    opportunityText: 'Сделка',
    regardingText: 'Тема',
    notesText: 'Заметки',
    resultText: 'Результат',
    categoryText: 'Категория',
    sendEmailText: 'Отправить по Эл. почте',
    sendToWordText: 'Передать в Word',
    addNoteText: 'Добавить заметку',
    completeAnActivityText: 'Завершить дело',
    helpText: 'Помощь',
    pleaseSelectRecordsText: 'Выберите одну или несколько записей',
    UnableToFindWordMsg: 'Невозможно запустить Microsoft Word.  Проверьте ваши установки по безопасности.',
    printedOnText: 'Напечатано на'
});