define({
    contractText: 'Контракт',
    contractRequiredText: 'Требуется контракт',
    sdataUrlText: 'URL SData',
    titleText: 'Название',
    usernameText: 'Имя Пользователя',
    passwordText: 'Пароль',
    logOnText: 'Вход',
    urlRequiredText: 'Требуется URL SData',
    urlImproperFormatText: 'URL SData имеет недопустимый формат.  Пример: http://localhost/sdata/slx/dynamic/-/',
    customNoAuthText1: 'Приносим извинения за неудобства, но ваш запрос не может быть выполнен. Данные авторизации для этого потока ошибочны или отсутствуют.',
    customNoAuthText2: 'Обновите имя пользователя и пароль для:',
    feedText: 'Поток SData',
    urlAuthenticationText: 'Введите пользовательский поток SData',
    selectFeedText: 'Выберите поток',
    nextText: 'Далее&gt;',
    warningText: 'Информация',
    invalidWhereText: 'Ошибка в предложении WHERE. Проверьте предложение WHERE на ошибки форматирования. Дополнительные сведения см. в разделе справки "Создание предложения WHERE".',
    failedToLoadUrlText: 'Не удалось загрузить запрошенный поток. Выберите другой поток или обратитесь к системному администратору.',
    noFeedSelectedText: 'Не выбран тип потока',
    resourceText: 'Ресурс',
    whereText: 'Оператор "Where"',
    previousText: '&lt;Назад',
    noResourceSelectedText: 'Выберите ресурс',
    noColumnsSelectedText: 'Выберите один или несколько столбцов для отображения в виджете.',
    limitRangeText: 'Введите значение от 1 до 100',
    testText: 'Тестировать',
    cancelText: 'Отмена',
    finishText: 'Завершить',
    exampleQueryText1: 'Пример:',
    exampleQueryText2: 'IP-адрес компьютера',
    exampleQueryText3: 'номер порта',
    exampleWhereText: 'Узнать больше',
    numberRecordsText: 'Видимые записи',
    sageSalesLogixDynamic: 'Динамический объект Saleslogix',
    sageSalesLogixSystem: 'Система Saleslogix',
    selectColumnsFromText: 'Доступные столбцы:',
    selectedColumnsFromText: 'Выбранные столбцы:'
});