define({
    loadingText: 'Caricamento...',
    moreText: 'Modificare gli elementi',
    clearText: 'Pulisci',
    emptyText: '(Vuoto)',
    nullText: '(Nullo)',
    ofText: '/',
    filterHasMetric: 'Ha metrica',
    filterHasFilter: 'Ha filtro',
    filteroptionToday: 'Oggi',
    filteroptionThisWeek: 'Questa settimana',
    filteroptionThisMonth: 'Questo mese',
    filteroptionThisQuarter: 'Questo trimestre',
    filteroptionThisYear: 'Quest\'anno',
    filteroptionLastWeek: 'Ultima settimana',
    filteroptionLastMonth: 'Ultimo mese',
    filteroptionLastQuarter: 'Ultimo trimestre',
    filteroptionLastYear: 'Ultimo anno',
    filteroptionWeektoStart: 'Settimana alla Data',
    filteroptionMonthtoStart: 'Mese alla data',
    filteroptionQtrtoStart: 'Trimestre alla data',
    filteroptionYeartoStart: 'Anno alla data',
    filteroptionOlder: 'Più vecchio'
});