define({
    contractText: 'Contratto',
    contractRequiredText: 'Contratto è richiesto',
    sdataUrlText: 'URL SData',
    titleText: 'Titolo',
    usernameText: 'Nome Utente',
    passwordText: 'Password',
    logOnText: 'Connetti',
    urlRequiredText: 'L\'URL SData è obbligatorio',
    urlImproperFormatText: 'Formato URL SData non valido. Esempio: http://localhost/sdata/slx/dynamic/-/',
    customNoAuthText1: 'Ci scusiamo per l\'inconveniente, ma non è possibile completare la richiesta. Le informazioni di autorizzazione per questo feed sono errate o mancanti.',
    customNoAuthText2: 'Aggiornare il proprio nome utente e password per:',
    feedText: 'Feed SData',
    urlAuthenticationText: 'Immettere un feed SData personalizzato',
    selectFeedText: 'Selezionare un feed',
    nextText: 'Avanti&gt;',
    warningText: 'Informazioni',
    invalidWhereText: 'La clausola where non è valida. Riesaminare la clausola where per eventuali errori di formattazione. Per ulteriori informazioni, vedere l\'argomento della guida "Creazione di una clausola Where".',
    failedToLoadUrlText: 'Impossibile caricare il feed richiesto. Selezionare un feed diverso o contattare l\'amministratore di sistema.',
    noFeedSelectedText: 'Nessun tipo di feed selezionato',
    resourceText: 'Risorsa',
    whereText: 'Where Clause',
    previousText: '&lt;Indietro',
    noResourceSelectedText: 'Selezionare una risorsa',
    noColumnsSelectedText: 'Selezionare una o più colonne da visualizzare nel widget.',
    limitRangeText: 'Immettere un valore 1-100',
    testText: 'Verifica',
    cancelText: 'Annulla',
    finishText: 'Fine',
    exampleQueryText1: 'Example:',
    exampleQueryText2: 'indirizzo IP macchina',
    exampleQueryText3: 'numero porta',
    exampleWhereText: 'Altre informazioni',
    numberRecordsText: 'Record visibili',
    sageSalesLogixDynamic: 'Entità dinamica di Saleslogix',
    sageSalesLogixSystem: 'Sistema Saleslogix',
    selectColumnsFromText: 'Colonne disponibili:',
    selectedColumnsFromText: 'Colonne selezionate:'
});