define((
{
    colNameEntityName: 'Имя',
    colNameType: 'Тип',
    colNameTable: 'Таблица',
    colNameCreateUser: 'Создано',
    colNameCreateDate: 'Дата создания',
    colNameLastExecutionDate: 'Последний запуск',
    colNameLastExecutionUser: 'Последний запуск от имени',
    colNameModifyUser: 'Кто обновил',
    colNameModifyDate: 'Дата обновления',
    colNameEntityDisplayName: 'Название',
    colNameEntityTableName: 'Таблица',
    colNamePropertyCount: 'Счетчик свойств',
    colNameFilterCount: 'Счетчик фильтров',
    colNameMetricCount: 'Счетчик метров',
    colNamePackage: 'Пакет',
    filterName: 'Имя',
    filterDisplayName: 'Название',
    filterEntityName: 'Название сущности',
    filterModifiedDate: 'Дата изменения',
    filterHasMeasure: 'Есть измерение',
    filterHasMetric: 'Есть метрика',
    filterHasFilter: 'Есть фильтр',
    filteroptionToday: 'Сегодня',
    filteroptionThisWeek: 'На этой неделе',
    filteroptionThisMonth: 'В этом месяце',
    filteroptionThisQuarter: 'В этот квартал',
    filteroptionThisYear: 'В этом году',
    filteroptionLastWeek: 'Последняя неделя',
    filteroptionLastMonth: 'Прошлый месяц',
    filteroptionLastQuarter: 'Прошлый квартал',
    filteroptionLastYear: 'Прошлый год',
    filteroptionOlder: 'Старше',
    lblFilterManager: 'Диспетчер фильтров',
    lblEntityManager: 'Диспетчер сущностей',
    FilterManager: 'Диспетчер фильтров',
    EntityManager: 'Диспетчер сущностей',
    lblEntity: 'Сущность',
    lblEntities: 'Сущности'
}
));