define({
    defaultWidgetText: 'Modificare le impostazioni dei Widget',
    settingsText: 'Impostazioni',
    viewGroupText: 'Visualizza Gruppo',
    Bar_Chart: 'Grafico a Barre',
    Column_Chart: 'Grafico a Colonne',
    Group_List: 'Elenco Gruppi',
    Pie_Chart: 'Grafico a Torta',
    Funnel_Chart: 'Grafico a Imbuto',
    Line_Chart: 'Grafico a Linee',
    SData_Feed: 'Feed SData',
    Web_Feed: 'Feed Web',
    Website: 'Sito Web',
    Default: 'Predefinito',
    Links: 'Collegamento',
    Recently_Viewed: 'Visto di recente',
    Todays_Activities: 'Attività di Oggi',
    Today_s_Activities: 'Attività di Oggi',
    Welcome: 'Benvenuto',
    Closing_Opportunities: 'Chiusura Opportunità',
    Quick_Actions: 'Azioni rapide',
    Do_You_Know___: 'Lo sai...',
    All_Leads: 'Tutti i Nominativi',
    My_Notes: 'Mie Note',
    Open_Opportunities: 'Opportunità aperte',
    My_Top_Opportunities: 'Miei Migliori Opportunità',
    My_Pipeline: 'Mia Pipeline',
    Recent_Lead_Creation_History: 'Cronologia Creazione Nominativo Recente',
    My_Activity_trend: 'Tendenza Mie Attività',
    My_Completed_Activities_by_Type: 'Mie Attività Completate per Tipo',
    Active_Campaigns: 'Campagne Attive',
    All_Open_Opportunities: 'Tutte le Opportunità Aperte',
    Top_Opportunities: 'Migliori opportunità',
    Open_Defect_Distribution: 'Distribuzione Difetti Aperti',
    My_Dashboard: 'Il Mio Cruscotto',
    Sales: 'Vendite',
    Group_List_Description: 'Visualizza un elenco di record raggruppati per entità. Ad esempio, un gruppo di campagne attive.',
    Welcome_Description: 'Visualizza un\'introduzione a Saleslogix con un collegamento all\'argomento della guida Introduzione alla parte Web Sage SalesLogix',
    Line_Chart_Description: 'Visualizza i dati sotto forma di punti connessi da una linea. Utile quando i dati rappresentano molti gruppi di categorie.',
    Bar_Chart_Description: 'Visualizza i dati sotto forma di barre orizzontali. Utile nel confronto dei dati.',
    Column_Chart_Description: 'Visualizza i dati sotto forma di barre verticali raggruppate per categoria. Utile per mostrare le modifiche ai dati in un determinato periodo di tempo o per illustrare confronti tra dati.',
    Funnel_Chart_Description: 'Visualizza i dati sotto forma di imbuto con proporzioni progressive. Il dato viene rappresentato come porzione del 100% e non ci sono assi.',
    Pie_Chart_Description: 'Visualizza i dati come porzioni dell\'intero. Ciascun valore è calcolato come percentuale del totale. Questo grafico non ha assi.',
    Recently_Viewed_Description: 'Visualizza i collegamenti ai record visitati di recente con un\'icona che identifica il tipo di record stesso. Ad esempio, Azienda o Contatto.',
    Todays_Activities_Description: 'Visualizza i collegamenti alle attività di oggi.',
    Links_Description: 'Visualizza i collegamenti che hai creato. Ad esempio, a una vista di dettaglio Saleslogix o ad un sito esterno.',
    SData_Feed_Description: 'Visualizza un feed Web utilizzando feed SData (Sage Data). Ad esempio, un feed dell\'integrazione contabilità o del database Saleslogix.',
    Web_Feed_Description: 'Visualizza informazioni su feed RSS o Atom.',
    Website_Description: 'Visualizza un sito Web scelto dall\'utente.'
});