define({
    yestText: 'Да',
    noText: 'Нет',
    confirmOverwriteFileMsg: 'На данный момент у вас есть выбранный файл импорта. Вы хотите заменить этот файл?',
    importProgressCaption: 'Результаты процесса импорта',
    lblPrimaryProgress: 'Обработка файла импорта, пожалуйста, подождите...',
    lblTotalRecords: 'Всего записей:',
    lblTotalRecordsProcessed: 'Обработано:',
    lblTotalRecordsImported: 'Импортировано:',
    lblTotalRecordsMerged: 'Объединено:',
    lblTotalDuplicates: 'Повторов:',
    lblTotalProjectedDuplicates: 'Ожидаемых повторов:',
    lblDuplicateRate: 'Доля повторов:',
    lblTotalErrors: 'Ошибок:',
    calculatingText: 'Вычисление, пожалуйста, подождите...',
    importStatusProcessing: 'Обработка',
    importStatusCompleted: 'Завершено',
    abortImportProcessStatus: 'Прервать',
    btnCancelText: 'Прервать',
    btnCloseText: 'Закрыть',
    lblImportHistoryLinkText: 'Чтобы увидеть результаты импорта, нажмите номер импорта в поле ниже:',
    lblImportLinkNumber: 'Номер Импорта:',
    errorRequestImportHistory: 'Произошла ошибка выполнения запроса SDATA для конечной точки importHistory.'
});