define({
    lblCreateSchedule: 'Créer un planning de tâches à exécuter',
    lblEveryText: 'Chaque',
    lblOnText: 'sur',
    lblOnTheText: 'le',
    lblAtText: 'à',
    lblMinutesPastHour: 'minutes après l\'heure',
    lblFromTimeText: 'Exécuter depuis',
    lblToTimeText: 'À',
    lblMinutesFrequency: 'Minutes',
    lblHourlyFrequency: 'Heure(s)',
    lblDailyFrequency: 'Jour',
    lblWeekDayFrequency: 'jour de la semaine',
    lblWeeklyFrequency: 'Semaine',
    lblMonthlyFrequency: 'Mois',
    lblYearlyFrequency: 'Année',
    lblSunday: 'Dimanche',
    lblMonday: 'Lundi',
    lblTuesday: 'Mardi',
    lblWednesday: 'Mercredi',
    lblThursday: 'Jeudi',
    lblFriday: 'Vendredi',
    lblSaturday: 'Samedi',
    lblFirstDay: 'Prénom',
    lblSecondDay: 'deuxième',
    lblThirdDay: 'troisième',
    lblFourthDay: 'quatrième',
    lblCronExpressionText: 'Expression Cron',
    txtInvalidScheduleTitle: 'Planification incorrecte',
    txtInvalidDatesMessage: 'La date de fin doit être postérieure à la date de début. Veuillez la corriger avant de continuer.',
    txtInvalidScheduleTime: 'Les dates de début et de fin spécifiées ne permettront pas à cette planification de s\'exécuter. Veuillez les corriger avant de continuer.',
    txtInvalidStartDate: 'Une date de début est requise. Veuillez en indiquer une avant de continuer.',
    txtInvalidEndDate: 'Une date de fin est requise. Veuillez en indiquer une avant de continuer'
});