define((
{
    colNameEntityName: 'Nom',
    colNameType: 'Type',
    colNameTable: 'Table',
    colNameCreateUser: 'Créé par',
    colNameCreateDate: 'Date de création',
    colNameLastExecutionDate: 'Dernière exécution',
    colNameLastExecutionUser: 'Dernière exécution par',
    colNameModifyUser: 'Modifié par',
    colNameModifyDate: 'Date de modification',
    colNameEntityDisplayName: 'Nom d\'affichage',
    colNameEntityTableName: 'Table',
    colNamePropertyCount: 'Nombre de propriétés',
    colNameFilterCount: 'Nombre de filtres',
    colNameMetricCount: 'Nombre de mesures',
    colNamePackage: 'Progiciel',
    filterName: 'Nom',
    filterDisplayName: 'Nom d\'affichage',
    filterEntityName: 'Nom de l\'entité',
    filterModifiedDate: 'Date de modification',
    filterHasMeasure: 'Comporte une unité de mesure',
    filterHasMetric: 'Comporte une mesure',
    filterHasFilter: 'Comporte un filtre',
    filteroptionToday: 'Aujourd\'hui',
    filteroptionThisWeek: 'Cette semaine',
    filteroptionThisMonth: 'Ce mois',
    filteroptionThisQuarter: 'Ce trimestre',
    filteroptionThisYear: 'Cette année',
    filteroptionLastWeek: 'Semaine dernière',
    filteroptionLastMonth: 'Mois dernier',
    filteroptionLastQuarter: 'Trimestre dernier',
    filteroptionLastYear: 'Année dernière',
    filteroptionOlder: 'Plus ancien',
    lblFilterManager: 'Gestionnaire de filtres',
    lblEntityManager: 'Gestionnaire d\'entités',
    FilterManager: 'GestionnaireFiltres',
    EntityManager: 'GestionnairesEntités',
    lblEntity: 'Entité',
    lblEntities: 'Entités'
}
));