define(
{
    txtGroup: 'Группа',
    txtDateRange: 'Временной диапазон',
    txtUser: 'Пользователь',
    txtQuery: 'Запрос',
    txtIsGreaterThan: 'Больше чем',
    txtIsLessThan: 'Меньше чем',
    txtIsInTheRange: 'В диапазоне',
    txtIsAfter: 'После',
    txtIsBefore: 'До',
    txtContains: 'Содержит',
    txtStartsWith: 'Начинается с',
    txtEndsWith: 'Заканчивается на',
    txtIs: 'это',
    txtIsNot: 'Не',
    txtOnDemand: 'По запросу',
    txtScheduled: 'Запланировано',
    txtCrystalReport: 'Отчет Crystal Report',
    txtExportToFileReportType: 'Выгрузить в файл',
    txtUnknownReportType: 'Неизвестен',
    txtNoFormat: 'Без формата',
    txtPdf: 'PDF',
    txtExcel: 'Excel',
    txtExcelDataOnly: 'Данные Excel',
    txtCsv: 'CSV',
    txtWord: 'Word',
    txtXml: 'XML'
});