define(
    {
        txtGroupFamily_Caption: 'Famille :',
        txtGroupName_Caption: 'Nom :',
        txtGroupDisplayName_Caption: 'Nom d\'affichage :',
        txtGroupDescription_Caption: 'Description :',
        txtGroupId_Caption: 'ID :',
        txtGroupMainTable_Caption: 'Tableau principal :',
        txtGroupEntityName_Caption: 'Nom de l\'entité :',
        txtGroupCreateDate_Caption: 'Date de création :',
        txtGroupCreateUser_Caption: 'Utilisateur de création :',
        txtGroupModifyDate_Caption: 'Date de modification :',
        txtGroupModifyUser_Caption: 'Modifier Utilisateur :',
        txtGroupInstallationDate_Caption: 'Date d\'installation :',
        txtGroupShared_Caption: 'Partagé:',
        txtGroupSharedDate_Caption: 'Date de partage :',
        txtGroupOwner_Caption: 'Propriétaire :',
        txtGroupUserId_Caption: 'ID utilisateur :',
        txtGroupAdhoc_Caption: 'Ad hoc :',
        txtGroupHidden_Caption: 'Masqué:',
        txtGroupAuthor_Caption: 'Auteur :',
        txtGroupCompany_Caption: 'Société :',
        txtGroupCompanyVersion_Caption: 'Version de la société :',
        txtGroupDev_Caption: 'Dév :',
        txtGroupDataCode_Caption: 'Code données :',
        txtGroupType_Caption: 'Type de groupe :',
        txtGroupBasedOn_Caption: 'Basé sur ID du groupe :',
        txtGroupReleasedToType_Caption: 'Partagé par Type :',
        txtGroupReleasedTo_Caption: 'Partagé par Nom :',
        txtGroupReleasedToTitle_Caption: 'Partagé par Titre :',
        txtGroupReleasedToUserType_Caption: 'Partagé par Type d\'utilisateur :'
    }
);