define((
{ dialogCaption: 'Détails du devis',
  loadingText: 'Chargement ...',
  lblSalesQuoteCaption: 'Devis :',
  lblStatusCaption: 'Etat :',
  lblGrossTotalCaption: 'Montant du devis :',
  lblQuoteDateCaption: 'Date du devis :',
  lblTaxTotalCaption: 'Montant de la taxe :',
  lblHoldStatusCaption: 'Statut en attente :',
  lblCurrencyCaption: 'Devise :',
  lblTypeCaption: 'Type :',
  lblCostTotalCaption: 'Coût total :',
  lblPONumberCaption: 'N° de BdC :',
  lblProfitTotalCaption: 'Total des bénéfices :',
  lblQuotationCaption: 'Devis :',
  lblInvoiceStatusCaption: 'Statut de la facture :',
  lblContactCaption: 'Contact :',
  lblDeliveryDateCaption: 'Date de livraison :',
  lblDueDateCaption: 'Date d\'échéance :',
  lblPriceListCaption: 'Liste de prix :',
  lblCarrierCaption: 'Transporteur :',
  lblNetTotalCaption: 'Total net :',
  lblAllocationStatusCaption: 'Statut d\'allocation :',
  lblDiscountTotalCaption: 'Total de la remise :',
  lblDeliveryStatusCaption: 'Statut de livraison :',
  lblChargesTotalCaption: 'Total facturé :',
  detailsTabTitle: 'Détails',
  salesPersonsTabTitle: 'Représentant commercial :',
  addressTabTitle: 'Adresses',
  salesQuoteLinesTabTitle: 'Lignes du devis',
  paymentsTabTitle: 'Paiements',
  deliveriesTabTitle: 'Livraisons',
  grdSalesQuote_Edit: 'Modifier',
  grdSalesQuote_QuoteNumber: 'Numéro du devis',
  grdSalesQuote_QuoteDate: 'Date du devis',
  grdSalesQuote_Status: 'Etat',
  grdSalesQuote_HoldStatus: 'Statut en attente',
  grdSalesQuote_Type: 'Type',
  grdSalesQuote_PO: 'Numéro de BdC',
  grdSalesQuote_NetTotal: 'Total net',
  grdSalesQuote_DiscountTotal: 'Total de la remise',
  grdSalesQuote_ChargesTotal: 'Total des frais',
  grdSalesQuote_TaxTotal: 'Montant de la taxe',
  grdSalesQuote_GrossTotal: 'Total brut',
  grdSalesQuote_Currency: 'Devise',
  grdSalesPersons_Name: 'Nom',
  grdSalesPersons_Type: 'Type',
  grdSalesPersons_Extension: 'Extension',
  grdSalesPersons_Relationship: 'Relation',
  grdAddress_Name: 'Nom',
  grdAddress_Address1: 'Adresse 1',
  grdAddress_Address2: 'Adresse 2',
  grdAddress_City: 'Ville',
  grdAddress_State: 'Département',
  grdAddress_Zip: 'Code postal',
  grdItems_Line: 'Numéro de la ligne',
  grdItems_Type: 'Type',
  grdItems_Commodity: 'Marchandise',
  grdItems_CommodityVariant: 'Variable',
  grdItems_CommodityDimension: 'Dimension',
  grdItems_UnitOfMeasure: 'Unité',
  grdItems_Location: 'Emplacement',
  grdItems_PriceList: 'Liste des prix',
  grdItems_Quantity: 'Quantité',
  grdItems_InitialPrice: 'Prix d\'origine',
  grdItems_ActualPrice: 'Prix réel',
  grdItems_NetTotal: 'Total net',
  grdItems_ChargesTotal: 'Total des frais',
  grdItems_DiscountTotal: 'Total de la remise',
  grdItems_TaxTotal: 'Montant de la taxe',
  grdItems_GrossTotal: 'Total brut',
  grdPayments_Date: 'Date du paiement',
  grdPayments_Name: 'Nom',
  grdPayments_Type: 'Type',
  grdPayments_Status: 'Etat',
  grdPayments_NetTotal: 'Total net',
  grdPayments_Discounts: 'Remises',
  grdPayments_Charges: 'Frais',
  grdPayments_Tax: 'TVA',
  grdPayments_GrossTotal: 'Total brut',
  grdPayments_Currency: 'Devise',
  grdPayments_TenderType: 'Type de l\'appel d\'offre',
  grdPayments_TenderReference: 'Référence de l\'appel d\'offre',
  grdPayments_ProcessDate: 'Date d\'exécution',
  grdDeliveries_Number: 'Nombre',
  grdDeliveries_Type: 'Type',
  grdDeliveries_Status: 'Etat',
  grdDeliveries_RequestedDate: 'Date de la demande',
  grdDeliveries_ActualDate: 'Date réelle',
  grdDeliveries_ActualTime: 'Heure réelle',
  grdDeliveries_RequestedQuantity: 'Quantité demandée',
  grdDeliveries_DeliveredQuantity: 'Quantité livrée',
  grdDeliveries_Method: 'Méthode',
  grdDeliveries_Carrier: 'Transporteur',
  grdDeliveries_CarrierReference: 'Référence du transporteur',
  grdDeliveries_ExceptionReason: 'Motif de l\'exception',
  errorERPRequest: 'Une erreur s\'est produite lors de l\'affichage des détails du devis des systèmes de comptabilité. ',
  errorERPRequestDetails: '${0}, ${1} Demande : ${2}',
  btnCloseCaption: 'Fermer' }
));