define((
{ dlgCrystalReportConditionDetails_Title: 'Bedingung hinzufügen/bearbeiten',
  cmdOK_Caption: 'OK',
  cmdCancel_Caption: 'Abbrechen',
  cmbConditionType_Caption: 'Abgleichen anhand von',
  txtInvalidParameterTitle: 'Ungültiger Parameter',
  txtInvalidParameterMessage: 'Ungültiger Parameter: ${0}',
  lkpUser_Caption: 'Benutzer',
  lkpGroup_Caption: 'Gruppe',
  txtSelectUser: 'Benutzer auswählen',
  chkCurrentUser_Caption: 'Aktueller Benutzer',
  txtName: 'Name',
  txtOK: 'OK',
  txtSelectGroup: 'Gruppe auswählen',
  cmbDateRange_Caption: 'Datumsbereich',
  cmbDateRange_SpecificDates_Caption: 'Bestimmte Termine',
  cmbDateRange_ThisWeek_Caption: 'Diese Woche',
  cmbDateRange_ThisMonth_Caption: 'Diesen Monat',
  cmbDateRange_ThisQuarter_Caption: 'Dieses Quartal',
  cmbDateRange_ThisYear_Caption: 'Dieses Jahr',
  cmbDateRange_LastWeek_Caption: 'Letzte Woche',
  cmbDateRange_LastMonth_Caption: 'Letzter Monat',
  cmbDateRange_LastQuarter_Caption: 'Letztes Quartal',
  cmbDateRange_LastYear_Caption: 'Letztes Jahr',
  cmbDateRange_MonthToDate_Caption: 'Monat Bis Heute',
  cmbDateRange_QuarterToDate_Caption: 'Quartal bis heute',
  cmbDateRange_YearToDate_Caption: 'Jahr bis heute',
  dtFromDate_Caption: 'Von',
  dtToDate_Caption: 'An',
  cmbTable_Caption: 'Tabelle',
  cmbField_Caption: 'Feld',
  cmbOperator_Caption: 'Operator',
  txtValue_Caption: 'Wert',
  txtNumericValueFrom_Caption: 'Von',
  txtNumericValueTo_Caption: 'An' }
));