define({
    lblCreateSchedule: 'Erstellen des Auftragszeitplans zur Ausführung',
    lblEveryText: 'Jede(n)',
    lblOnText: 'am',
    lblOnTheText: 'am',
    lblAtText: 'um',
    lblMinutesPastHour: 'Minuten nach der vollen Stunde',
    lblFromTimeText: 'Ausführen von',
    lblToTimeText: 'bis',
    lblMinutesFrequency: 'Minuten',
    lblHourlyFrequency: 'Stunde(n)',
    lblDailyFrequency: 'Tag',
    lblWeekDayFrequency: 'Wochentag',
    lblWeeklyFrequency: 'Woche',
    lblMonthlyFrequency: 'Monat',
    lblYearlyFrequency: 'Jahr',
    lblSunday: 'Sonntag',
    lblMonday: 'Montag',
    lblTuesday: 'Dienstag',
    lblWednesday: 'Mittwoch',
    lblThursday: 'Donnerstag',
    lblFriday: 'Freitag',
    lblSaturday: 'Samstag',
    lblFirstDay: 'ersten',
    lblSecondDay: 'zweiten',
    lblThirdDay: 'dritten',
    lblFourthDay: 'vierten',
    lblCronExpressionText: 'Cron-Ausdruck',
    txtInvalidScheduleTitle: 'Ungültiger Zeitplan',
    txtInvalidDatesMessage: 'Die Endzeit muss hinter der Startzeit liegen. Korrigieren Sie diese Informationen, bevor Sie fortfahren.',
    txtInvalidScheduleTime: 'Die angegebenen Start- und Endzeiten verhindern ein Ausführen des Zeitplans. Korrigieren Sie die Informationen, bevor Sie fortfahren.',
    txtInvalidStartDate: 'Ein Startdatum ist erforderlich. Geben Sie ein Startdatum ein, bevor Sie fortfahren.',
    txtInvalidEndDate: 'Ein Enddatum ist erforderlich. Geben Sie ein Enddatum ein, bevor Sie fortfahren.'
});