/*globals Sage, dojo, dojox, dijit, Simplate, window, Sys, define */
define([
    /* Sage/tests/UI */
    "Sage/tests/UI/_DetailPane",
    "Sage/tests/UI/_DetailPanelConfigurationProvider",
    "Sage/tests/UI/_DialogLoadingMixin",
    "Sage/tests/UI/_TitlePaneConfigProvider",
    "Sage/tests/UI/ComboBox",
    "Sage/tests/UI/ConditionManager",
    "Sage/tests/UI/DateTextBox",
    "Sage/tests/UI/DetailPanel",
    "Sage/tests/UI/Dialogs",
    "Sage/tests/UI/EditableGrid",
    "Sage/tests/UI/EditorContainer",
    "Sage/tests/UI/FilteringSelect",
    "Sage/tests/UI/GridContainer",
    "Sage/tests/UI/GridMenuItem",
    "Sage/tests/UI/GroupListConfigurationProvider",
    "Sage/tests/UI/GroupMenuFmtScope",
    "Sage/tests/UI/GroupsTitlePaneConfigProvider",
    //"Sage/tests/UI/GroupTabPane", // Performance test - run stand alone
    "Sage/tests/UI/ImageButton",
    "Sage/tests/UI/JsonPrintDetailPane",
    "Sage/tests/UI/ListPanel",
    "Sage/tests/UI/MenuBar",
    "Sage/tests/UI/MenuBarItem",
    "Sage/tests/UI/MenuItem",
    "Sage/tests/UI/NavBar",
    "Sage/tests/UI/NavBarPane",
    "Sage/tests/UI/NumberTextBox",
    "Sage/tests/UI/OrientableMenuBar",
    "Sage/tests/UI/PopupMenuBarItem",
    "Sage/tests/UI/PopupMenuItem",
    "Sage/tests/UI/SDataLookup",
    "Sage/tests/UI/SDataMainViewConfigurationProvider",
    "Sage/tests/UI/SearchConditionWidget",
    "Sage/tests/UI/SearchMenuItem",
    "Sage/tests/UI/SLXPreviewGrid",
    "Sage/tests/UI/SpeedSearch",
    "Sage/tests/UI/SummaryContainer",
    "Sage/tests/UI/SummaryContents",
    "Sage/tests/UI/SummaryDetailPane",
    "Sage/tests/UI/SummaryFormatterScope",
    "Sage/tests/UI/TextBox",
    "Sage/tests/UI/TitleContentPane",
    "Sage/tests/UI/ToggleButton",
    "Sage/tests/UI/ToolBarLabel",
    "Sage/tests/UI/UniqueToListValidationTextBox",
    "Sage/tests/UI/URL",
    "Sage/tests/UI/WidgetEditor",
    "Sage/tests/UI/widgetEditorLookup",
    // Sub-Folder Content
    "Sage/tests/UI/Alarms/testLoader",
    "Sage/tests/UI/Columns/testLoader",
    "Sage/tests/UI/Controls/testLoader",
    "Sage/tests/UI/Dashboard/testLoader",
    "Sage/tests/UI/Filters/testLoader"
    
], function() {
});