define((
{
    colNameEntityName: 'Nome',
    colNameType: 'Tipo',
    colNameTable: 'Tabella',
    colNameCreateUser: 'Creato da',
    colNameCreateDate: 'Data Creazione',
    colNameLastExecutionDate: 'Ultima Esecuzione',
    colNameLastExecutionUser: 'Ultima esecuzione di',
    colNameModifyUser: 'Utente Modifica',
    colNameModifyDate: 'Data Modifica',
    colNameEntityDisplayName: 'Visualizza Nome',
    colNameEntityTableName: 'Tabella',
    colNamePropertyCount: 'Conteggio proprietà',
    colNameFilterCount: 'Conteggio filtro',
    colNameMetricCount: 'Conteggio metrica',
    colNamePackage: 'Pacchetto',
    filterName: 'Nome',
    filterDisplayName: 'Visualizza Nome',
    filterEntityName: 'Nomeentita',
    filterModifiedDate: 'Data modifica',
    filterHasMeasure: 'Ha misura',
    filterHasMetric: 'Ha metrica',
    filterHasFilter: 'Ha filtro',
    filteroptionToday: 'Oggi',
    filteroptionThisWeek: 'Questa settimana',
    filteroptionThisMonth: 'Questo mese',
    filteroptionThisQuarter: 'Questo trimestre',
    filteroptionThisYear: 'Quest\'anno',
    filteroptionLastWeek: 'Ultima settimana',
    filteroptionLastMonth: 'Ultimo mese',
    filteroptionLastQuarter: 'Ultimo trimestre',
    filteroptionLastYear: 'Ultimo anno',
    filteroptionOlder: 'Precedente',
    lblFilterManager: 'Gestore filtri',
    lblEntityManager: 'Gestore entità',
    FilterManager: 'GestoreFiltri',
    EntityManager: 'GestoreEntità',
    lblEntity: 'Entità',
    lblEntities: 'Entità'
}
));