define((
{
        // Add/Edit labels
        lblFilter: "Filter",
        lblMetric: "Metrik",
        lblFilters: "Filter",
        lblMetrics: "Kennzahlen",
        lblDistinct: "Eindeutig",
        lblRange: "Bereich",
        lblUserLookup: "Benutzersuche",
        lblAdd: "Hinzufügen",
        lblEdit: "Bearbeiten",
        lblRemove: "Entfernen",
        lblHelp: 'Hilfe',
        lblFilterName: "Filtername",
        lblMetricName: "Kennzahlname",
        lblDisplayName: "Anzeigename",
        lblFilterDp: "Felder",
        lblTypeDp: "Typ",
        lblCharacter:"Zeichen",
        lblFrom: "Von",
        lblTo: "An",
        lblOperators: "Operatoren",
        lblAggregation: "Aggregationen",
        lblTypeSpecificContentBox: "Typspezifischer Inhaltsbereich",
        lblSaveButton: "OK",
        lblCancelButton: "Abbrechen",
        DateDiffCheckerValue: "Kennzahl zum Datumsunterschied",
        InvalidFilterName: "Ungültiger Filtername",
        InvalidRangeName: "Ungültiger Bereichsname",
        RequiredFilterName: "Filtername ist erforderlich",
        RequiredRangeName: "Bereichsname ist erforderlich",
        FieldMustBeANumber: "Im Feld 'Zeichen' muss eine Ganzzahl eingegeben werden.",
        SelectAnItem: "Wählen Sie ein Element aus.",
        ItemRequired: "Element erforderlich",
        ItemInvalid: "Element ungültig",
        LowerMustBeLessThanUpper: "Unterer Wert muss kleiner sein als oberer Wert.",
        defaultRangeRowValue: "Wert eingeben",
        totalRecordCountLabel: "Gesamtzahl Datensätze: ${0}"
    }
));