define(
{
    txtGroup: 'Groupe',
    txtDateRange: 'Intervalle de dates',
    txtUser: 'Utilisateur',
    txtQuery: 'Requête',
    txtIsGreaterThan: 'Est supérieur à',
    txtIsLessThan: 'Est inférieur à',
    txtIsInTheRange: 'Est compris dans l\'intervalle',
    txtIsAfter: 'Vient après',
    txtIsBefore: 'Vient avant',
    txtContains: 'contient',
    txtStartsWith: 'Commence par',
    txtEndsWith: 'Finit par',
    txtIs: 'Est',
    txtIsNot: 'N’est pas',
    txtOnDemand: 'À la demande',
    txtScheduled: 'Planifié',
    txtCrystalReport: 'Crystal Report',
    txtExportToFileReportType: 'Exporter vers un fichier',
    txtUnknownReportType: 'Inconnu',
    txtNoFormat: 'Aucun format',
    txtPdf: 'PDF',
    txtExcel: 'Excel',
    txtExcelDataOnly: 'Données Excel',
    txtCsv: 'CSV',
    txtWord: 'Word',
    txtXml: 'XML'
});