define((
{ dialogCaption: 'Angebotsdetails',
  loadingText: 'Wird geladen...',
  lblSalesQuoteCaption: 'Angebot:',
  lblStatusCaption: 'Status:',
  lblGrossTotalCaption: 'Angebotsbetrag:',
  lblQuoteDateCaption: 'Angebotsdatum:',
  lblTaxTotalCaption: 'Steuer gesamt:',
  lblHoldStatusCaption: 'Status Aussetzen:',
  lblCurrencyCaption: 'Währung:',
  lblTypeCaption: 'Typ:',
  lblCostTotalCaption: 'Gesamtkosten:',
  lblPONumberCaption: 'Bestellnummer:',
  lblProfitTotalCaption: 'Gesamtgewinn:',
  lblQuotationCaption: 'Angebot:',
  lblInvoiceStatusCaption: 'Rechnungsstatus:',
  lblContactCaption: 'Kontakt:',
  lblDeliveryDateCaption: 'Lieferdatum:',
  lblDueDateCaption: 'Fälligkeitsdatum:',
  lblPriceListCaption: 'Preisliste:',
  lblCarrierCaption: 'Versanddienst:',
  lblNetTotalCaption: 'Nettosumme:',
  lblAllocationStatusCaption: 'Zuordnungsstatus:',
  lblDiscountTotalCaption: 'Rabatt gesamt:',
  lblDeliveryStatusCaption: 'Lieferstatus:',
  lblChargesTotalCaption: 'Gesamtkosten:',
  detailsTabTitle: 'Details',
  salesPersonsTabTitle: 'Verkäufer',
  addressTabTitle: 'Adressen',
  salesQuoteLinesTabTitle: 'Angebotszeilen',
  paymentsTabTitle: 'Zahlungen',
  deliveriesTabTitle: 'Lieferungen',
  grdSalesQuote_Edit: 'Bearbeiten',
  grdSalesQuote_QuoteNumber: 'Angebotsnummer',
  grdSalesQuote_QuoteDate: 'Angebotsdatum',
  grdSalesQuote_Status: 'Status',
  grdSalesQuote_HoldStatus: 'Status Aussetzen',
  grdSalesQuote_Type: 'Typ',
  grdSalesQuote_PO: 'Bestellnummer',
  grdSalesQuote_NetTotal: 'Nettosumme',
  grdSalesQuote_DiscountTotal: 'Rabatt gesamt',
  grdSalesQuote_ChargesTotal: 'Gesamtkosten',
  grdSalesQuote_TaxTotal: 'Steuer gesamt',
  grdSalesQuote_GrossTotal: 'Summe brutto',
  grdSalesQuote_Currency: 'Währung',
  grdSalesPersons_Name: 'Name',
  grdSalesPersons_Type: 'Typ',
  grdSalesPersons_Extension: 'Erweiterung',
  grdSalesPersons_Relationship: 'Beziehung',
  grdAddress_Name: 'Name',
  grdAddress_Address1: 'Zahlungsmittelsreferenz',
  grdAddress_Address2: 'Adresse2',
  grdAddress_City: 'Stadt',
  grdAddress_State: 'Bundesland/Kanton',
  grdAddress_Zip: 'PLZ',
  grdItems_Line: 'Positionsnummer',
  grdItems_Type: 'Typ',
  grdItems_Commodity: 'Ware',
  grdItems_CommodityVariant: 'Variante',
  grdItems_CommodityDimension: 'Dimension',
  grdItems_UnitOfMeasure: 'Einheit',
  grdItems_Location: 'Standort',
  grdItems_PriceList: 'Preisliste',
  grdItems_Quantity: 'Menge',
  grdItems_InitialPrice: 'Ausgangspreis',
  grdItems_ActualPrice: 'Tatsächlicher Preis',
  grdItems_NetTotal: 'Nettosumme',
  grdItems_ChargesTotal: 'Gesamtkosten',
  grdItems_DiscountTotal: 'Rabatt gesamt',
  grdItems_TaxTotal: 'Steuer gesamt',
  grdItems_GrossTotal: 'Summe brutto',
  grdPayments_Date: 'Zahlungsdatum',
  grdPayments_Name: 'Name',
  grdPayments_Type: 'Typ',
  grdPayments_Status: 'Status',
  grdPayments_NetTotal: 'Nettosumme',
  grdPayments_Discounts: 'Rabatte',
  grdPayments_Charges: 'Kosten',
  grdPayments_Tax: 'Steuer',
  grdPayments_GrossTotal: 'Summe brutto',
  grdPayments_Currency: 'Währung',
  grdPayments_TenderType: 'Zahlungsmitteltyp',
  grdPayments_TenderReference: 'Zahlungsmittelreferenz',
  grdPayments_ProcessDate: 'Verarbeitungsdatum',
  grdDeliveries_Number: 'Zahl',
  grdDeliveries_Type: 'Typ',
  grdDeliveries_Status: 'Status',
  grdDeliveries_RequestedDate: 'Angefordert am',
  grdDeliveries_ActualDate: 'Tatsächliches Datum',
  grdDeliveries_ActualTime: 'Tatsächliche Uhrzeit',
  grdDeliveries_RequestedQuantity: 'Angeforderte Menge',
  grdDeliveries_DeliveredQuantity: 'Gelieferte Menge',
  grdDeliveries_Method: 'Methode',
  grdDeliveries_Carrier: 'Versanddienst',
  grdDeliveries_CarrierReference: 'Versanddienstreferenz',
  grdDeliveries_ExceptionReason: 'Begründung der Ausnahme',
  errorERPRequest: 'Beim Öffnen der Angebotsdetailansicht im Buchhaltungssystem ist ein Fehler aufgetreten.',
  errorERPRequestDetails: '${0}, ${1} Anforderung: ${2}',
  btnCloseCaption: 'Schließen' }
));