define((
{ dlgReportScheduleDetails_Schedule_Title: 'Add/Edit Schedule',
  dlgReportScheduleDetails_RunReport_Title: 'Run Report',
  txtReportType_Caption: 'Report Type',
  txtReportName_Caption: 'Report Name',
  txtOutputFormat_Caption: 'Format',
  txtRunAs_Caption: 'Run As',
  txtScheduleName_Caption: 'Schedule Name',
  txtScheduleDescription_Caption: 'Description',
  cmbScheduleFrequency_Caption: 'Frequency',
  cmbArchive_Caption: 'Archive reports older than',
  dtStartTime_Caption: 'Run From',
  dtEndTime_Caption: 'Run To',
  txtRepeatCount_Caption: 'Repeat Count',
  txtRepeatInterval_Caption: 'Repeat interval',
  cmdOK_Caption: 'OK',
  cmdCancel_Caption: 'Cancel',
  tabSchedule_Caption: 'Schedule Details',
  txtOnDemandScheduleName: 'On Demand',
  txtReportSuccessfullyScheduled: 'Report successfully scheduled.',
  dlgScheduleReport_Title: 'Schedule Report',
  txtName: 'Name',
  txtSelectUser: 'Select User',
  txtOK: 'OK' }
));