define((
{
    colNameEntityName: 'Name',
    colNameType: 'Type',
    colNameTable: 'Table',
    colNameCreateUser: 'Create User',
    colNameCreateDate: 'Create Date',
    colNameLastExecutionDate: 'Last Run',
    colNameLastExecutionUser: 'Last Run By',
    colNameModifyUser: 'Modify User',
    colNameModifyDate: 'Modify Date',
    colNameEntityDisplayName: 'Display Name',
    colNameEntityTableName: 'Table',
    colNamePropertyCount: 'Property Count',
    colNameFilterCount: 'Filter Count',
    colNameMetricCount: 'Metric Count',
    colNamePackage: 'Package',
    filterName: 'Name',
    filterDisplayName: 'Display Name',
    filterEntityName: 'Entity Name',
    filterModifiedDate: 'Modified Date',
    filterHasMeasure: 'Has Measure',
    filterHasMetric: 'Has Metric',
    filterHasFilter: 'Has Filter',
    filteroptionToday: 'Today',
    filteroptionThisWeek: 'This Week',
    filteroptionThisMonth: 'This Month',
    filteroptionThisQuarter: 'This Quarter',
    filteroptionThisYear: 'This Year',
    filteroptionLastWeek: 'Last Week',
    filteroptionLastMonth: 'Last Month',
    filteroptionLastQuarter: 'Last Quarter',
    filteroptionLastYear: 'Last Year',
    filteroptionOlder: 'Older',
    lblFilterManager: 'Filter Manager',
    lblEntityManager: 'Entity Manager',
    FilterManager: 'FilterManager',
    EntityManager: 'EntityManager',
    lblEntity: 'Entity',
    lblEntities: 'Entities'
}
));