define((
{
        // Add/Edit labels
        lblFilter: "Filtro",
        lblMetric: "Metrica",
        lblFilters: "Filtri",
        lblMetrics: "Metriche",
        lblDistinct: "Singolo",
        lblRange: "Intervallo",
        lblUserLookup: "Ricerca Utente",
        lblAdd: "Aggiungi",
        lblEdit: "Modifica",
        lblRemove: "Rimuovi",
        lblHelp: 'Aiuto',
        lblFilterName: "Nome Filtro",
        lblMetricName: "Nome metrica",
        lblDisplayName: "Visualizza Nome",
        lblFilterDp: "Fields",
        lblTypeDp: "Tipo",
        lblCharacter:"Carattere",
        lblFrom: "Da",
        lblTo: "A",
        lblOperators: "Operators",
        lblAggregation: "Aggregazioni",
        lblTypeSpecificContentBox: "Casella contenuto di tipo specifico",
        lblSaveButton: "OK",
        lblCancelButton: "Annulla",
        DateDiffCheckerValue: "Data metrica differente",
        InvalidFilterName: "Nome Filtro Non valido",
        InvalidRangeName: "Nome metrica non valido",
        RequiredFilterName: "Nome filtro obbligatorio",
        RequiredRangeName: "Nome intervallo obbligatorio",
        FieldMustBeANumber: "Il campo Carattere deve essere un numero intero",
        SelectAnItem: "Selezionare un elemento",
        ItemRequired: "Elemento obbligatorio",
        ItemInvalid: "Elemento non valido",
        LowerMustBeLessThanUpper: "Il valore inferiore deve essere più piccolo del valore superiore.",
        defaultRangeRowValue: "Immettere un valore",
        totalRecordCountLabel: "Totale record: ${0}"
    }
));