define({
    dlgManageImportOptions_Title: 'Importazione record - Opzioni',
    lstImportType_Caption: 'Cosa fare con i record in questo file?',
    lstImportOption_Insert: 'Aggiungi record se non vengono trovate corrispondenze',
    txtOption_Insert: 'Un nuovo record contatto, account o indirizzo verrà aggiunto al database se non è possibile trovare un record esistente in base ai criteri di corrispondenza definiti. Se viene trovato un record corrispondente, il record non verrà importato.',
    lstImportOption_Update: 'Aggiorna record se viene trovata una corrispondenza',
    txtOption_Update: 'Se viene trovato un record contatto, account o indirizzo esistente in base ai criteri di corrispondenza definiti, il record verrà aggiornato con le informazioni importate. Se non viene trovato un record corrispondente, le informazioni nonn verranno importate.',
    lstImportOption_InsertUpdate: 'Aggiungi o aggiorna ogni record',
    txtOption_InsertUpdate: 'Se viene trovato un record contatto, account o indirizzo esistente in base ai criteri di corrispondenza definiti, il record verrà aggiornato con le informazioni importate. Se non viene trovato un record corrispondente, verrà aggiunto un nuovo record.',
    txtMatchHeader_Caption: 'Definisci i criteri di corrispondenza:',
    txtOptionsHeader_Caption: 'Opzioni',
    defaultOwner_Caption: 'Proprietario Predefinito:',
    lookupDefaultOwner_Caption: 'Ricerca Proprietario',
    lookupDescriptionColText: 'Descrizione',
    lookupTypeColText: 'Tipo',
    createAdHoc_Caption: 'Crea un nuovo Gruppo Ad Hoc',
    existingAdHoc_Caption: 'Aggiungi ad un Gruppo Ad Hoc esistente',
    errorNoAddHocGroupName: 'Specificare un nome di Gruppo Ad hoc prima di continuare.',
    match_Caption: 'Corrispondenza:',
    invalidMappingAssociation: 'Prima di continuare è necessario specificare ogni proprietà di corrispondenza nella mappatura delle proprietà.'
});