define(
{
    txtGroup: 'Gruppo',
    txtDateRange: 'Intervallo data',
    txtUser: 'Utente',
    txtQuery: 'Query',
    txtIsGreaterThan: 'è maggiore di',
    txtIsLessThan: 'è inferiore a',
    txtIsInTheRange: 'è nell\'Intervallo',
    txtIsAfter: 'Dopo',
    txtIsBefore: 'Prima',
    txtContains: 'Contiene',
    txtStartsWith: 'Inizia per',
    txtEndsWith: 'Termina Con',
    txtIs: 'E\'',
    txtIsNot: 'Non è',
    txtOnDemand: 'Su richiesta',
    txtScheduled: 'Pianificato',
    txtCrystalReport: 'Crystal Reports',
    txtExportToFileReportType: 'Esporta nel File',
    txtUnknownReportType: 'Sconosciuto',
    txtNoFormat: 'Nessun formato',
    txtPdf: 'PDF',
    txtExcel: 'Excel',
    txtExcelDataOnly: 'Dati Excel',
    txtCsv: 'CSV',
    txtWord: 'Word',
    txtXml: 'XML'
});