define((
{ ToDo: 'Impegno',
  PhoneCall: 'Telefonata',
  Meeting: 'Riunione',
  Personal: 'Attività Personale',
  Literature: 'Materiale informativo',
  Fax: 'Corretto nella Versione:',
  Letter: 'Lettera',
  Note: 'Nota',
  Email: 'E-mail',
  Document: 'Documento',
  DatabaseChange: 'Modifica DB',
  Event: 'Evento',
  ScheduledEvent: 'Evento Pianificato',
  Contact: 'Contatto',
  Lead: 'Nominativo',
  New: 'Nuovo',
  Change: 'Modifica',
  Deleted: 'Eliminato',
  Confirm: 'Conferma',
  Decline: 'Rifiuta',
  Unknown: 'Sconosciuto',
  Leader: 'Responsabile',
  Complete: 'Completa',
  confirmTypeChanged: 'Cambiato',
  confirmTypeConfirmed: 'Confermato',
  confirmTypeDeleted: 'Eliminato' }
));