define({
    txtPleaseSpecifyValue: 'Specificare un valore.',
    lblAvailableValues_Caption: 'Valori disponibili:',
    lblSelectedValues_Caption: 'Valori selezionati:',
    lblEnterValue_Caption: 'Immettere un valore:',
    btnOK_Caption: 'OK',
    txtTheValueMustBeBetween: 'Il valore deve contenere tra {0} e {1} caratteri.',
    txtTheMinimumLengthForThisField: 'La lunghezza minima di questo campo è {0}.',
    txtTheMaximumLengthForThisField: 'La lunghezza massima di questo campo è {0}.',
    txtPleaseSpecifyNumberBetween: 'Specificare un valore numerico compreso tra b{0} e {1}.',
    txtPleaseSpecifyNumberLesser: 'Specificare un valore numerico minore o uguale a {0}.',
    txtPleaseSpecifyNumberGreater: 'Specificare un valore numerico maggiore o uguale a {0}.',
    txtNoLowerValue: 'Valore inferiore mancante',
    txtNoUpperValue: 'Valore superiore mancante',
    txtIncludeThisValue: 'Includi questo valore',
    txtFrom: 'Da:',
    txtTo: 'A:',
    txtPleaseSpecifyFromValue: 'Specificare il valore iniziale dell\'intervallo',
    txtPleaseSpecifyToValue: 'Specificare il valore finale dell\'intervallo',
    txtPleaseSpecifyDateBetween: 'Specificare un valore data compreso tra {0} e {1}.',
    txtPleaseSpecifyDateLesser: 'Specificare un valore data minore o uguale a {0}.',
    txtPleaseSpecifyDateGreater: 'Specificare un valore data maggiore o uguale a {0}.',
    txtFromMustBeLessThanOrEqualToTo: 'Il valore iniziale dell\'intervallo deve essere minore o uguale al valore finale.',
    txtStartOfRange: 'Inizio intervallo:',
    txtEndOfRange: 'Fine intervallo:',
    txtAddRange: 'Add Range',
    lblSelectValue_Caption: 'Selezionare un valore:',
    lblOrValue_Caption: 'O'
});