define({
    dlgManageImportOptions_Title: 'Importation des enregistrements - Options',
    lstImportType_Caption: 'Que souhaitez-vous faire avec les enregistrements de ce fichier ?',
    lstImportOption_Insert: 'Ajouter l\'enregistrement si aucune correspondance n\'a été trouvée',
    txtOption_Insert: 'Un nouvel enregistrement de contact, de compte ou d\'adresse sera ajouté à la base de données si les critères de correspondance définis ne renvoient aucun enregistrement existant. Si un enregistrement correspondant est trouvé, l\'enregistrement ne sera pas importé.',
    lstImportOption_Update: 'Mettre à jour l\'enregistrement en cas de correspondance',
    txtOption_Update: 'Si les critères de correspondance définis renvoient un enregistrement de contact, de compte ou d\'adresse existant, l\'enregistrement sera mis à jour avec les informations importées. Si aucun enregistrement correspondant n\'est trouvé, les informations ne sont pas importées.',
    lstImportOption_InsertUpdate: 'Ajouter ou mettre à jour chaque enregistrement',
    txtOption_InsertUpdate: 'Si les critères de correspondance définis renvoient un enregistrement de contact, de compte ou d\'adresse existant, l\'enregistrement sera mis à jour avec les informations importées. Si aucun enregistrement correspondant n\'est trouvé, un nouvel enregistrement sera ajouté.',
    txtMatchHeader_Caption: 'Définir les critères de correspondance :',
    txtOptionsHeader_Caption: 'Options',
    defaultOwner_Caption: 'Propriétaire par défaut :',
    lookupDefaultOwner_Caption: 'Rechercher un propriétaire',
    lookupDescriptionColText: 'Description',
    lookupTypeColText: 'Type',
    createAdHoc_Caption: 'Créer un nouveau groupe ad hoc',
    existingAdHoc_Caption: 'Ajouter au groupe ad hoc existant',
    errorNoAddHocGroupName: 'Veuillez spécifier un nom de groupe ad hoc avant de continuer.',
    match_Caption: 'Correspondance :',
    invalidMappingAssociation: 'Chaque correspondance de propriété doit être spécifiée dans les mappages de propriétés avant de continuer.'
});