define((
{ svAccount_Caption: 'Compte :',
  svCompany_Caption: 'Société :',
  svEmail_Caption: 'E-mail :',
  svName_Caption: 'Nom :',
  svTitle_Caption: 'Titre :',
  svType_Caption: 'Type :',
  svSubType_Caption: 'Sous-type :',
  svAccMgr_Caption: 'Resp. du compte :',
  svHomePhone_Caption: 'N° de téléphone domicile :',
  svWorkPhone_Caption: 'N° de téléphone prof. :',
  svMobilePhone_Caption: 'Téléphone mobile :',
  svStatus_Caption: 'Etat :',
  svWebAddress_Caption: 'Web :',
  svEntityAccount_Caption: 'Compte',
  svEntityLead_Caption: 'Lead',
  svEntityContact_Contact: 'Contact',
  svTollFree_Caption: 'Numéro vert :',
  svIndustry_Caption: 'Secteur :',
  svDivision_Caption: 'Division :',
  svMainPhone_Caption: 'Téléphone principal :',
  LeadSummaryView_Title: 'Vue Résumé - Lead',
  ContactSummaryView_Title: 'Vue Résumé - Contact',
  AccountSummaryView_Title: 'Vue Résumé - Compte',
  closeText: 'Fermer',
  errorLoadingSummaryView: 'Une erreur s\'est produite lors du chargement de la vue Résumé : ${0}' }
));