define(
    {
        txtGroupFamily_Caption: 'Familie:',
        txtGroupName_Caption: 'Name:',
        txtGroupDisplayName_Caption: 'Anzeigename:',
        txtGroupDescription_Caption: 'Beschreibung:',
        txtGroupId_Caption: 'ID:',
        txtGroupMainTable_Caption: 'Haupttabelle:',
        txtGroupEntityName_Caption: 'Entitätsname:',
        txtGroupCreateDate_Caption: 'Erstellungsdatum:',
        txtGroupCreateUser_Caption: 'Angelegt von:',
        txtGroupModifyDate_Caption: 'Änderungsdatum:',
        txtGroupModifyUser_Caption: 'Geändert von:',
        txtGroupInstallationDate_Caption: 'Installationsdatum:',
        txtGroupShared_Caption: 'Freigegeben:',
        txtGroupSharedDate_Caption: 'Freigabedatum:',
        txtGroupOwner_Caption: 'Zugriffsber.:',
        txtGroupUserId_Caption: 'Benutzer-ID:',
        txtGroupAdhoc_Caption: 'Ad-hoc:',
        txtGroupHidden_Caption: 'Ausgeblendet:',
        txtGroupAuthor_Caption: 'Autor:',
        txtGroupCompany_Caption: 'Unternehmen:',
        txtGroupCompanyVersion_Caption: 'Unternehmensversion:',
        txtGroupDev_Caption: 'Dev:',
        txtGroupDataCode_Caption: 'Datencode:',
        txtGroupType_Caption: 'Gruppentyp:',
        txtGroupBasedOn_Caption: 'Basierend auf Gruppen-ID:',
        txtGroupReleasedToType_Caption: 'Freigegeben für Typ:',
        txtGroupReleasedTo_Caption: 'Freigegeben für Name:',
        txtGroupReleasedToTitle_Caption: 'Freigegeben für Titel:',
        txtGroupReleasedToUserType_Caption: 'Freigegeben für Benutzertyp:'
    }
);