define({
    loadingText: 'Chargement ...',
    moreText: 'Modifier les éléments',
    clearText: 'Effacer',
    emptyText: '(Vide)',
    nullText: '(Nul)',
    ofText: '/',
    filterHasMetric: 'A une mesure Web',
    filterHasFilter: 'A un filtre',
    filteroptionToday: 'Aujourd\'hui',
    filteroptionThisWeek: 'Cette semaine',
    filteroptionThisMonth: 'Ce mois',
    filteroptionThisQuarter: 'Ce trimestre',
    filteroptionThisYear: 'Cette année',
    filteroptionLastWeek: 'Semaine dernière',
    filteroptionLastMonth: 'Mois dernier',
    filteroptionLastQuarter: 'Trimestre dernier',
    filteroptionLastYear: 'Année dernière',
    filteroptionWeektoStart: 'Semaine à ce jour',
    filteroptionMonthtoStart: 'Mois à ce jour',
    filteroptionQtrtoStart: 'Trimestre à ce jour',
    filteroptionYeartoStart: 'Année à ce jour',
    filteroptionOlder: 'Plus ancien'
});