define({
    yestText: 'Ja',
    noText: 'Nein',
    confirmOverwriteFileMsg: 'Es ist eine Importdatei ausgewählt. Möchten Sie diese Datei überschreiben?',
    importProgressCaption: 'Ergebnisse des Importvorgangs',
    lblPrimaryProgress: 'Importdatei wird verarbeitet - bitte warten...',
    lblTotalRecords: 'Datensätze gesamt:',
    lblTotalRecordsProcessed: 'Verarbeitet:',
    lblTotalRecordsImported: 'Importiert:',
    lblTotalRecordsMerged: 'Zusammengeführt:',
    lblTotalDuplicates: 'Duplikate:',
    lblTotalProjectedDuplicates: 'Projektierte Duplikate:',
    lblDuplicateRate: 'Duplikatrate:',
    lblTotalErrors: 'Fehler:',
    calculatingText: 'Berechnung läuft. Bitte warten ...',
    importStatusProcessing: 'Verarbeitung läuft',
    importStatusCompleted: 'Abgeschlossen',
    abortImportProcessStatus: 'Abbrechen',
    btnCancelText: 'Abbrechen',
    btnCloseText: 'Schließen',
    lblImportHistoryLinkText: 'Zum Anzeigen der Importhistorienergebnisse klicken Sie unten auf die Importnummer:',
    lblImportLinkNumber: 'Importnummer: ',
    errorRequestImportHistory: 'Fehler beim Ausführen der SData-Anforderung für den Endpunkt Importhistorie.'
});