define({
    root: {
        txtGroupFamily_Caption: 'Family:',
        txtGroupName_Caption: 'Name:',
        txtGroupDisplayName_Caption: 'Display Name:',
        txtGroupDescription_Caption: 'Description:',
        txtGroupId_Caption: 'ID:',
        txtGroupMainTable_Caption: 'Main Table:',
        txtGroupEntityName_Caption: 'Entity Name:',
        txtGroupCreateDate_Caption: 'Create Date:',
        txtGroupCreateUser_Caption: 'Create User:',
        txtGroupModifyDate_Caption: 'Modify Date:',
        txtGroupModifyUser_Caption: 'Modify User:',
        txtGroupInstallationDate_Caption: 'Installation Date:',
        txtGroupShared_Caption: 'Shared:',
        txtGroupSharedDate_Caption: 'Shared Date:',
        txtGroupOwner_Caption: 'Owner:',
        txtGroupUserId_Caption: 'User ID:',
        txtGroupAdhoc_Caption: 'Ad Hoc:',
        txtGroupHidden_Caption: 'Hidden:',
        txtGroupAuthor_Caption: 'Author:',
        txtGroupCompany_Caption: 'Company:',
        txtGroupCompanyVersion_Caption: 'Company Version:',
        txtGroupDev_Caption: 'Dev:',
        txtGroupDataCode_Caption: 'Data Code:',
        txtGroupType_Caption: 'Group Type:',
        txtGroupBasedOn_Caption: 'Based on Group ID:',
        txtGroupReleasedToType_Caption: 'Shared to Type:',
        txtGroupReleasedTo_Caption: 'Shared to Name:',
        txtGroupReleasedToTitle_Caption: 'Shared to Title:',
        txtGroupReleasedToUserType_Caption: 'Shared to User Type:'
    },
    'de': true,
    'en': true,
    'fr': true,
    'it': true,
    'ru': true
});